- src/IsaacAppTypes.tsx
- src/app/components/elements/TrustedHtml.tsx
- src/test/components/TrustedHtml.test.tsx
This allows use of `EXAM_BOARD` as a user preference to determine which boolean algebra syntax will be displayed to the user. We default to "mathematician syntax", as used in propositional and formal logic and by the OCR exam board.
> KaTeX Rendering by Exam Board Preference

- src/app/components/elements/ListGroupFooterBottom.tsx
- src/app/components/navigation/CookieBanner.tsx
- src/app/components/navigation/EmailVerificationBanner.tsx
- src/app/components/navigation/Footer.tsx
- src/app/components/navigation/Header.tsx
- src/scss/isaac.scss
- src/scss/print.scss
We may want to move these into their relevant existing SCSS files?
To preview this most easily, [follow these instructions for Chrome](https://developers.google.com/web/tools/chrome-devtools/css/print-preview).
Also, removes some things that shouldn't be printed.
> Add very minimal print CSS configuration

- src/app/components/pages/Search.tsx
- src/app/services/examBoard.ts
- src/app/services/topics.ts
- Moves filterOnExamBoard to `examBoard` service from the `topics` service.
- Filters search results based on user specified exam board
- Provides Anon user choice like topics in the filter section
> Add exam board filtering to search results

- public/index.html
- src/index.tsx
This cannot easily be previewed locally, because the stylesheets are loaded by JavaScript in the development server. To actually see the page locally, you need to build the minified version and then serve it using a static server (e.g. `python2 -m SimpeHTTPServer 8003`) from the `build` directory.
The layout falls back gracefully without CSS though!
I'm not sure I like `rootElement.classList.add("min-vh-100");`, but the class is required to make sure the page takes up the full height, and it does add an unnecessary scroll-bar on the noscript page if left in by default. Adding it by JavaScript seems an acceptable compromise for these two?
> Make the noscript page look nicer using Bootstrap classes and logo

- src/app/components/navigation/IsaacApp.tsx
All routes in IsaacApp now use exact to stop substring matches.
Previously 'path="/teachers"' would also match the path
"/teachers/non-existant-path"
> Use exact for all routes to stop substring matchs

- public/assets/Line-alt.svg
- public/assets/Line.svg
- src/scss/header.scss
The header previously consister of repeated svg lines. This produced
white stripes in Chrome at certain zoom levels.
Fixed by simply resizing the svg to cover the required area
> Replace repeating background with css resized

- src/app/components/elements/PageFragment.tsx
- src/app/components/handlers/ShowLoading.tsx
Previously a Page fragment 404 would result in a small 404 page being
shown. Components such as the second breadcrumb bar made this look
strange.
Fixed by allowing a custom 404 element to be shown for ShowLoading
elements.
> Stop nesting for Page fragment 404 errors

- src/app/components/elements/TrustedHtml.tsx
- src/app/services/katex-a11y.js
This is based on a library that was created by the KaTeX/Khan Academy team, but is quite heavily modified to change the way certain expressions are described. It aims to make them simpler, but may lead to less clear descriptions in obscure cases. (E.g. integrals and sums now get limits descibed as `sum from, ..., to ...., of ....`, and common fractions like a half are now read as `one half`).
Tested with a large sample of physics and CS content!
This may want reviewing if KaTeX/KaTeX#820 or KaTeX/KaTeX#2072 produce anything more useful or general than my edited version of the library.
> Add accessible alternative text to KaTeX equations

- src/app/components/pages/EventDetails.tsx
Adds users to the waiting list if past the booking deadline, even if there are spaces available.
We might want to look at how we decide how many places are available for the events team.
> Allow users to join waiting list post booking deadline

- src/app/components/content/IsaacFigure.tsx
- src/app/components/elements/TrustedHtml.tsx
- src/app/components/elements/TrustedMarkdown.tsx
- src/app/components/elements/WithFigureNumbering.tsx
- src/test/components/TrustedHtml.test.tsx
The logic of figure identifiers is the same as in the Angular system.
I haven't implemented any kind of hyperlinking; that seems like an extra feature and might not be that clear.
> Figure numbering: show Figure N for \ref to figures

- src/app/components/elements/cards/EventCard.tsx
- src/app/components/elements/cards/NewsCard.tsx
- src/scss/cards.scss
- src/scss/homepage.scss
Now we have an events page as well as the homepage, the override styling on the homepage appears redundant and adds confusion so I removed it. Now event card images have their own class
> Restyle and rename class to differentiate event cards from news

- src/app/components/pages/Admin.tsx
- src/app/services/constants.ts
This uses the editor as a redirect proxy to GitHub; but the editor is already configured with the correct GitHub repo to use in all cases, and so this prevents duplicated configuration.
> Add a button to allow previewing of content version changes

- src/IsaacAppTypes.tsx
- src/app/components/elements/cards/EventCard.tsx
- src/app/components/pages/EventDetails.tsx
- src/app/services/events.tsx
We assume that the start time of the first in the series and the end time of the last event are the same for all events, at least when showing on the pods and pages.
> Format dates for recurring events differently

- src/app/components/content/IsaacSymbolicQuestion.tsx
- src/app/components/elements/modals/InequalityModal.tsx
- src/app/services/questions.ts
- src/scss/common/questions.scss
This required moving the parse function out from inside the modal, since we also need to use it to sanitise the displayed list. Since we also now use it outside, we need to remove `_no_alphabet` too.
> Show the list of available symbols underneath the text entry box

- package-lock.json
- package.json
- src/app/components/elements/modals/InequalityModal.tsx
Upgrades `inequality` to 0.9.22 which includes a bug fix. Apparently Windows 10 now reports `window.innerWidth` correctly so we don't need the crazy trick with the device pixel ratio. Who knew…
Needs checking that this doesn't break it for every other platform. Works for me on macOS with Chrome and Firefox.
> Potentially fix Windows 10 centering bug when OS UI is zoomed.

- src/app/components/elements/modals/InequalityModal.tsx
State was being set even though no actual change was present. Odd that React wouldn't detect that, but hey.
> Drastically reduce the amount of re-renders while using Inequality

- src/app/components/elements/panels/TeacherConnections.tsx
The tooltip per default isn't allowed to exceed the bounds of it's scroll parent (the table).
The first row would break the tooltip if one or two groups were present as there wasn't enough space for the tooltip to be placed.
> Prevent tooltip crashing the page and causing a memory leak.

- src/app/components/content/IsaacNumericQuestion.tsx
- src/app/components/content/IsaacSymbolicQuestion.tsx
- src/scss/common/questions.scss
- Restores tooltip for numeric answers.
- Uses `useMemo` to generate the tooltip element's id (https://github.com/reactstrap/reactstrap/issues/773#issuecomment-577976353).
> Restore numeric tooltip and fix up tooltip id generation.

- src/app/components/content/IsaacCard.tsx
- src/app/components/pages/TeacherFeatures.tsx
- src/scss/phy/menu-page-phy.scss
Adds a imageClassName parameter to the IsaacCard type.
Add CSS using the class name to restore the teacher features images to their original size.
> Fix oversized teacher features images caused by IsaacCard introduction

- src/app/components/content/IsaacHints.tsx
- src/app/components/elements/Tabs.tsx
- src/app/components/pages/MyProgress.tsx
- src/app/components/pages/Support.tsx
- Resumes logging which hints are viewed now they are hints
- Doesn't conflict with the CS hint modal logging
> Add hint logging for physics hint tabs with hint index

- src/app/components/content/IsaacSymbolicQuestion.tsx
If a user types "Tsin(theta)" this will be parsed as "T\*s\*i\*n\*theta", which is not what the user intended. Whilst this is visible, in the fact that the result has italic and not upright letters for the sin in the preview, this fact is not obvious to most users. Instead add a warning underneath.
We have to allow "a" and "c" as characters before to allow "asin(x)" or "arcsin(x)", and this seems the simplest regex to achieve this.
> Add a warning for users typing unclear function calls in text entry

- src/app/components/pages/GameboardBuilder.tsx
- src/scss/common/button.scss
This should reduce the chance of people accidentally clicking "create gameboard" before they are finished because the buttons will be of equal(-ish) emphasis.
> Change Add Questions to button with text and icon

- src/app/components/elements/FastTrackProgress.tsx
- src/app/state/actions.tsx
Progress within the session on concept questions was not being maintained between page changes.
A refresh used to be needed to get the concept progress of other quesitons, now we reload it on page change.
> Re-request FastTrack concept state on page change

- src/app/components/pages/AssignmentProgress.tsx
- src/app/components/pages/Groups.tsx
- src/scss/common/groups.scss
- Makes it more obvious if a teacher (with access revoked by student) is looking through their manage groups page
- Adds same greying out and removing of link to assignment progress page for unauthorised users
> Remove link from unauthorised users viewing progress

- package-lock.json
- src/app/components/elements/modals/InequalityModal.tsx
For some reason, some of the hyperbolic functions were in the trig functions list, and so would get included in the wrong menu tab as well as in the correct menu tab.
This fixes this mistake.
> Remove hyperbolic functions from trig functions menu.

- src/app/components/content/IsaacParsonsQuestion.tsx
It is sometimes desirable to prevent items from being indented in Parsons problems. This uses the `IsaacParsonsQuestionDTO::disableIndentation` flag to achieve the effect. This will require a toggle control to be added in the editor to turn the flag on and off.
> Support disabling indentation for Parsons problems

- src/app/components/elements/DateString.ts
- src/app/components/elements/views/ActivityGraph.tsx
This replaces #332, and simplifies the code dramatically. The only real difference is that this assumes that the API will provide zero values for months with no activity, and that it will only provide months when activity is meaningful. Currently this is all handled by Postgres, so it seems unlikely that this will go away even if the API changes dramatically.
It also now includes the months that were zero from registration as it used to, which may not actually be desired?
> Simplify and update My Progress page activity graph

- src/app/components/elements/modals/InequalityModal.tsx
When the order of a derivative is 1 and there is a compound numerator (i.e., one with a single letter) the letter would not appear on the canvas.
This fixes the issue.
> Fix a bug with complete derivatives in menu

- src/app/components/elements/modals/ReservationsModal.tsx
At the moment we disable the "All" checkbox if there are invalid (unverified) users in the "unbooked" table of the reservations modal. This PR modifies the selection code to exclude users that are invalid from the "All" selection when that checkbox is ticked.
> Prevent "Select All" of invalid unreserved users.

- src/app/components/elements/PageFragment.tsx
- src/app/components/elements/WithFigureNumbering.tsx
- src/app/components/navigation/TrackedRoute.tsx
The main problem with supporting figure numbering is that you can have multiple page fragments on a single page and the figure numbers should not restart from 1 for each fragment.
We now create a figure numbering "scope" for each page - unfortunately implemented by piggy-backing on the already overloaded TrackedRoute component.
I believe that it would be possible for a page with two page fragments to load out of order so that Figure 2 appears before Figure 1 on the final rendered page but that did not happen in my constructed page. Even then, each reference would still at least be unique.
No examples exist in the wild so I constructed a page with two page fragments each containing a unique Figure and figure reference (details to reproduce in last paragraph).
It certainly isn't perfect but …
> Add figure numbering to page fragments

- compose
- compose-etl
- compose-live
This also improves the validation of inputs initially and before they get passed into docker-compose, which seemed sensible.
It also removes the "special-case" nature of the test database initialisation; since the Docker Postgres image will not use the init
scripts if the data directory is blank, it ought to be safe to include the test scheme for all non-prod databases. Doing this dramatically simplifies the compose script.
This also restricts the types of docker-compose commands that can be run, to prevent passing unexpected things into it. If any commands have been missed, they can easily be added and a helpful error is printed.
> Allow the compose scripts to manage both physics and CS containers

- src/app/components/elements/MainSearch.tsx
- src/app/components/pages/Search.tsx
- src/app/services/constants.ts
Adds a 255 character limit to the search boxes, before a user hits the 1000 character backend bad request
> Soft limit search character length to 255

- src/app/services/api.ts
- src/app/services/constants.ts
This PR has an accompanying backend PR.
This will allow the content team to safely tag Maths questions as both `book` and `problem_solving` questions.
In the future, the filter will surface a question category selection (for Physics at least).
> Force physics filter to specify problem solving questions

- src/app/components/elements/modals/InequalityModal.tsx
Apparently now we have to use `onTouchEnd` to intercept click events on iOS.
> Restore functionality to Inequality number menu on iOS 14

- src/app/components/navigation/DowntimeWarningBanner.tsx
Might be worth someone checking those `new Date(...)` calls as well as me, but they are supposed to be the Wednesday before and going away at 9am on the day.
> Update the downtime warning banner for the planned Easter maintenance

- package-lock.json
- package.json
- src/app/components/content/IsaacCodeSnippet.tsx
- src/app/services/highlightJsConfig.ts
highlightBlock has been deprecated and replaced with highlightElement
> Upgrade highlightjs to 11.0.0 and reduce bundle size

- src/app/components/pages/quizzes/QuizDoFreeAttempt.tsx
As this functionality is intended to change in future this adds a temporary front end error modification if a quiz a user is trying to attempt has already been assigned to them by one or more teachers.
The modification provides a link to the `/quizzes` page so they can find their quiz assignment(s)
> Add temporary front end quiz error modification

- src/app/components/site/cs/NavigationBarCS.tsx
- src/app/components/site/cs/RoutesCS.tsx
I don't think anything else needs changing here, and it works seemingly as intended locally
> Add link to events safeguarding page in navbar

- src/IsaacAppTypes.tsx
- src/app/components/pages/MyProgress.tsx
- src/scss/common/search.scss
- Data comes as a ContentSummaryDTO so can't simply show whether it's correct or not, just a list of the 5 most recently attempted questions and the 5 oldest incomplete/incorrect.
> Render 5 most recent and oldest question attempts on the progress page

- src/IsaacApiTypes.tsx
- src/app/components/content/IsaacNumericQuestion.tsx
- src/scss/phy/subjects.scss
In line with James' API pull request, the existence of a non-null/non-empty `displayUnit` overrides `requireUnits`
If the question has a `displayUnit`, the unit dropdown is *essentially* disabled - it's default value is set to the `displayUnit`,
the colour is changed so the dropdown doesn't stand out as much, the caret is removed, it is permanently closed etc.
When there is a `displayUnit` the dropdown is still registered as clickable. This isn't ideal but the same can be said for the
numeric modal help button thingy (nothing happens when it gets clicked, but changes the mouse pointer etc.), so unless 
there's an easy fix I don't think it matters that much.
> Add displayUnit support for numeric questions

- src/app/components/elements/quiz/QuizAttemptComponent.tsx
This doesn't interfere with previewing or doing a quiz, it now only sets the section title to be a link if detailed feedback is selected.
> Only give a link to a quiz section if feedbackMode is set to detailed

- src/app/components/pages/AdminContentErrors.tsx
A really small change to add a filter to the admin content errors page. The filter checks whether the search string is included in any of the error messages in the list inside each `ContentErrorItem`
> Add simple filter to content errors

- src/app/components/elements/inputs/BooleanNotationInput.tsx
- src/app/services/constants.ts
Then followed through and patched anywhere it was previously used.
Since the enum only has two inhabitants, all of the code for reducing over it etc. seems quite heavy, but it shouldn't really impact performance and at least it's very extensible.
> Purged `NONE` from `BOOLEAN_NOTATION` enum

- src/app/components/elements/modals/InequalityModal.tsx
We have been seeing front-end errors reporting:
TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
at.componentWillUnmount (https://isaacphysics.org/...
This should fix that but I have not determined the true cause to reproduce.
> Checks for canvas before trying to remove it

- src/app/components/pages/AdminContentErrors.tsx
Added two checkboxes to `admin/content_errors`, to show errors for published and/or unpublished content.
> Add filters for published state of content

- src/app/services/assignments.ts
This just removes filtering by due date, as proposed and preferred by Physics content team
> Sort older assignments only by latest creation date first

- src/app/components/elements/inputs/UserContextAccountInput.tsx
Also hide check box when "all stages" and "all boards" are selected (since it doesn't do anything in this case)
> Change text of "other content" checkbox

- src/app/state/selectors.tsx
Hides group and student names from Set/Manage tests, and when looking at individual students attempts at tests.
> Demo mode hide group and student names in tests

- package-lock.json
- src/app/components/content/IsaacSymbolicLogicQuestion.tsx
- src/app/components/content/IsaacSymbolicQuestion.tsx
- src/app/components/pages/Equality.tsx
Apparently, we had already fixed this in other components but the phy/math one was stilly bugged.
> Avoid showing "Careful!" when the errors array is empty

- src/scss/phy/filter.scss
This is because it doesn't work and is rendered weirdly. Nicki would like it fixed properly but said this was okay for now, since actually fixing it will be extremely difficult. 
I've tested on Chrome, Edge, Firefox and Safari and only on Safari is it hidden.
> Hide "Coming soon" hexagon tag on Safari

- src/app/components/pages/SingleAssignmentProgress.tsx
This just changes a selector from one that fetches the raw assignment progress from the redux state, to one that goes through our `selectors` API. Affects `/assignment_progress/{assignmentId}`:
> Anonymise single assignment progress

- src/app/components/pages/MyAccount.tsx
This is not a nice bug!
On the account page sometimes edits which were "saved" were not being persisted.
The main object that we are altering from the account page forms is the `userToUpdate`.
`userToUpdate` can either be the `user` themselves or `userToEdit` if it is an admin that is using the page to alter someone else's details.
To accomodate changes from the Required Account Information modal being visible in `userToUpdate` we have a `useEffect` which updates `userToUpdate` to be either `user` or `userToEdit` whenever either of them change.
`userToEdit` gets wrapped to include a `loggedIn` field in a rather hacky way so that it looks like a normal user when it is being validated.
That wrapping created a new instance of `userToEdit` each time any part of redux state was changed, which …
> Fix lost account change information

- src/app/components/elements/quiz/QuizProgressCommon.tsx
- src/app/components/pages/AssignmentProgress.tsx
- src/scss/common/assignment-progress.scss
It does now! Plus the overall mark column is now sticky to the right of the table (which seemed to be what the old CSS was trying to do anyway)
A lot of the diff is cleaning up old code to make the linter happy (turning `let` into `const`, that kind of thing)
> Manage Tests / Assignment Progress (tests): student performance overflows window, doesn't scroll

- src/app/components/elements/MetaDescription.tsx
- src/app/components/elements/PageTitle.tsx
- src/app/components/pages/AllTopics.tsx
- src/app/components/pages/Concept.tsx
- src/app/components/pages/Contact.tsx
- src/app/components/pages/Events.tsx
- src/app/components/pages/GameboardFilter.tsx
- src/app/components/pages/Generic.tsx
- src/app/components/pages/Glossary.tsx
- src/app/components/pages/LogIn.tsx
- src/app/components/pages/Registration.tsx
- src/app/components/pages/Support.tsx
As suggested by Meurig in #523, use a single element for the meta description tags.
Also set the `og:title` (used by Facebook and Twitter, but only if set without JavaScript I fear) in the same way that page titles are set, so that it matches the title on all pages. This may not do anything.
> Improved meta descriptions

- src/app/state/modalFocusMiddleware.ts
- src/app/state/store.tsx
This fixes an accessibility issue where a modal popping up resets the focused element. It adds Redux middleware that records the last focused element before a modal opens, and restores it on modal close (or resets focus to the top of the main content if no element exists).
When this is tested, the team that does might want to try navigating the teacher gameboard builder with a screen-reader to make sure it is as accessible as needed.
> Focus last focused element on modal close

- src/app/components/elements/PageTitle.tsx
- src/app/components/elements/TitleAndBreadcrumb.tsx
- src/app/components/pages/MyProgress.tsx
- src/test/components/elements/TitleAndBreadcrumb.test.tsx
With this change a new optional `disallowLaTeX` parameter is used by the My Progress page to prevent LaTeX in student names from rendering in the page title or breadcrumb trail.
Other pages using TitleAndBreadcrumb are unaffected (can be tested with this [test page](https://editor.isaaccomputerscience.org/#!/edit/master/content/_test/_latex_title_test.json)).
> Add TitleAndBreadcrumb parameter to optionally disable LaTeX rendering

- src/app/components/pages/EventDetails.tsx
Account for other states in which a user's booking can be when deciding if they should see the waiting list message.
> Fix bug showing the waiting list message inappropriately

- src/app/components/pages/EventDetails.tsx
The previously added check (which I have overwritten) correctly hid the `book a place` button when a user already had a booking with an allowed status to see it. However it stopped the button showing for events with wait_list_only as their status for users that don't have a booking already, phy extensively make use of this to validate students before promoting them to a full booking.
I have tested this as a student and a teacher, on events with and without wait lists and the `book a place` button (dis)appears correctly
> Alter logic to show waiting list button

- src/app/components/content/IsaacClozeQuestion.tsx
Prior to the fix (on `/test/preview/quiz_alevel_boolean_01/page/1?examBoard=all&stage=all`):
This fix works by falling back to the `doc.id` if `questionPart.id` is `undefined`. Whether this is the right move or whether the question part id should be defined is something I'm not sure about.
> Fallback to `doc.id` if `questionPart.id` doesn't exist on cloze question quiz previews

- src/app/components/pages/GameboardFilter.tsx
This doesn't necessarily address the possibility of the gameboard not showing up when the URL is loaded, but I haven't been able to reproduce that and can't see a reason for it happening if it does - I just need to ask CS content for examples I think.
> Allow gameboard filter to populate exam board from URL properly

- config/webpack.config.common.js
We were not bundling the KaTeX fonts correctly, because the `css-loader` being used to import them was ignoring all URL rewriting so sometimes they would not load correctly in a production build.
The problem is that we use the `create-react-app` folder `public` for all of our assets, both those Webpack wants to know about and those that really are static and not part of the bundle. So instead of using Webpack as it intended, we just bluntly copy the `public/assets` folder to the `/assets` path and we turned off URL rewriting so this would work. But the turning off affected things beyond our special assets folder. So this fix, which is a bit hacky, is just to treat the `/assets` URL as a special case and rewrite anything else.
(The only other changes are to give bundled images and fonts …
> Fix KaTeX fonts and Webpack bundling

- src/app/components/pages/GameboardFilter.tsx
- src/app/services/miscUtils.ts
After this, a URL such as `/gameboards/new?difficulties=practice_1&topics=the_internet,communication` will correctly populate the question finder. Examboard and stage information was optional anyway.
> Don't express subject and field in CS question finder URL

- src/IsaacAppTypes.tsx
- src/app/components/elements/LaTeX.tsx
- src/app/components/elements/TrustedHtml.tsx
- src/test/components/TrustedHtml.test.tsx
Also shows screenreader text when hovering over math on all `DEV` platforms, which may improve focus on accessible content.
As far as I can tell this is only a net benefit, although there may be equations where:
- `katex-a11y` can't support them
- The MathML generated as a fall-back is awful when parsed by a screenreader
In this edge case, probably quoting "Unsupported equation" is better than a long string of nonsense from the parsed MathML.
This change also requires users to have a screenreader that supports MathML (as well as anyone testing accessibility). The one I've been using is the [Access8Math addon for NVDA](https://addons.nvda-project.org/addons/access8math.en.html). I reckon that any visually impaired user who is seriously using platforms containing math content will have a …
> Generate MathML for any LaTeX currently unsupported by katex-a11y

- config/webpack.config.cs.renderer.js
- config/webpack.config.phy.renderer.js
- package.json
- src/app/components/elements/EditorRenderer.tsx
A couple of things needed changing, I think because the webpack version changed.
I also send a message in to the opener/parent, which makes it possible to co-ordinate when to send messages.
> Update based on package updates; tell opener/parent when ready

- src/app/components/content/IsaacClozeQuestion.tsx
- src/app/components/elements/LaTeX.tsx
- src/app/components/elements/TrustedHtml.tsx
Drop zones were not rendering because of two passes of turning HTML into React portals, one passes to add tables and one to add drop-zones.
> Render tables using old method if tables are inside a cloze question

- src/app/components/content/IsaacCodeSnippet.tsx
- src/app/components/elements/ScrollShadows.tsx
- src/app/components/elements/TrustedHtml.tsx
More specifically, anything that doesn't support `window.ResizeObserver`
> Don't render `ScrollShadows` on Safari <= 13

- src/app/components/elements/modals/InequalityModal.tsx
This also hides the particles tab when available symbols are specified and changes the 'Elements' tab label according to whether it only contains elements or also contains particles. Elements are kept in the label even if the menu only contains particles to avoid breaking consistency
> Add a particles tab back to Inequality's menu

- src/IsaacAppTypes.tsx
- src/app/components/content/IsaacClozeQuestion.tsx
- src/app/components/content/IsaacCodeSnippet.tsx
- src/app/components/content/IsaacGlossaryTerm.tsx
- src/app/components/elements/ScrollShadows.tsx
- src/app/components/elements/Tabs.tsx
- src/app/components/elements/TrustedHtml.tsx
- src/app/components/elements/TrustedMarkdown.tsx
- src/app/components/elements/portals/GlossaryTerms.tsx
- src/app/components/elements/portals/InlineDropZones.tsx
- src/app/components/elements/portals/Tables.tsx
- src/app/components/elements/portals/utils.ts
**Disclaimer**: this was complicated, and the following explanation may be incoherent, so a demo of the code in person would be best for someone wanting to review it.
---
This presents and implements a pattern for portal components to be nested. This sounds nasty, but if we want things like tables, glossary terms and cloze question drop zones to be handled in React, it needs to be figured out - after abstracting some things, it's nicer than it seems at first glance!
The main idea is to use [callback refs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) to allow portal components to be re-rendered when the ref of the element they should be rending inside updates. The other idea is to make sure that any component using `dangerouslySetInnerHTML={{__html: html}}` is in charge of …
> Allow portal components dynamically created from content (glossary terms, tables) to be nested

- src/app/components/navigation/IsaacApp.tsx
- src/app/services/search.ts
This is no longer required, as arbitrary pages may be tagged with 'regression_test' for the same behaviour.
> Remove hardcoded special cases for regression test page

- src/app/components/elements/modals/ReservationsModal.tsx
User cannot have their booking cancelled twice via the UI, since the checkbox is disabled, and `cancelReservationCheckboxes` does not include those related to users who have cancelled bookings.
> Show users with cancelled bookings as de-emphasised rows in "manage reservations" modal

- src/app/services/quiz.ts
The circular dependency no longer seems to be an issue (maybe since some files are lazy loaded)
> Remove question type duplication in `quiz.ts`

- src/app/components/content/IsaacClozeQuestion.tsx
- src/app/components/elements/markup/portals/InlineDropZones.tsx
- src/app/components/elements/markup/portals/Tables.tsx
- src/app/services/clozeQuestionKeyboardSensor.ts
- src/app/services/katex-a11y.js
- src/scss/common/questions.scss
- src/scss/common/scroll.scss
This takes `useKeyboardSensor` from `react-beautiful-dnd`, and adds some extra (nasty) stuff so that it behaves as expected with cloze questions. Since you can only interact with one cloze question at a time, this should work fine in theory, and is certainly better than the non-functioning keyboard interaction we had already. It is now actually possible to answer a cloze question only using the keyboard.
If the question re-renders underneath a drag, the drag will cancel if it can't find any elements - this shouldn't really happen much, if at all.
I also changed around some ids so that `react-beautiful-dnd` gives nice screenreader messages. There is a small chance that multiple cloze questions on a single page could break because of this, but looking at the docs it seems like …
> Hack to get keyboard interaction working on cloze questions

- src/app/components/content/IsaacQuestion.tsx
- src/app/components/content/IsaacQuickQuestion.tsx
- src/app/components/elements/inputs/ConfidenceQuestions.tsx
The issue was that the question flow could be corrupted by the user answering twice in quick succession (within the window of the server returning a response to an attempt), so if a validation was pending, the we needed to be able to cancel the pending state change to the confidence buttons if another answer was submitted. 
Beforehand I tried to do this with a crude work-around that ended up not working.
Doing this properly just involved allowing the `useConfidenceQuestionsValues` hook to manage the `validationPending` state, meaning it could reset it if the current attempt changes.
This PR also fixed the confidence questions not working on item questions.
> Move `validationPending` state up to allow post question to show safely

- src/app/components/elements/modals/UserBookingModal.tsx
- src/app/components/elements/panels/AddUsersToBooking.tsx
- src/app/components/pages/EventDetails.tsx
- src/app/services/events.tsx
- src/app/state/actions.tsx
This PR removes references to the waiting list for WAITING_LIST_ONLY events, so it should be clearer to guests that they are actually requesting one of the available places (this is how WAITING_LIST_ONLY is used in practice).
> Rename waiting list to request a place for waiting list only events

- package.json
- yarn.lock
- drops Differentials while flattening Derivatives
- avoids confusion with mixed numbers while generating LaTeX code
> Upgrade Inequality to include bug fixes

- config/webpack.config.cs.renderer.js
- config/webpack.config.phy.renderer.js
- src/app/components/elements/EditorRenderer.tsx
- src/app/components/elements/inputs/ConfidenceQuestions.tsx
- src/app/services/constants.ts
- src/react-app-env.d.ts
Just amounts to allowing it to query an API. I chose staging to be consistent with the editor but maybe live would be preferable? - I'm not sure
> Allow editor preview to render glossary terms

- src/app/components/content/IsaacClozeQuestion.tsx
This also improves readability a bit. 
I've reverted the IDs, so they're no longer unique, but have removed the `htmlFor` attribute from the item section `Label` so that browsers don't get confused if there are multiple item sections on screen. We don't really need that label for screen reader purposes since the item section element has an `aria-label`, and `react-beautiful-dnd` produces nice messages anyway.
> Changes to item section ID for screen reader messages

- src/app/components/elements/MainSearch.tsx
- src/app/components/pages/Search.tsx
- src/app/services/search.ts
This PR fixes the search bar in the top-right on the /search page.
This is achieved by making the query in the URL query params the definitive source for queries sent to the server. Interacting with filters and input fields changes the URL; then the URL fields are used for sending to the server.
> Allow the top-right search bar to work on the /search page

- src/app/components/pages/Search.tsx
This avoids the request being sent twice for queries from the top-right search bar.
> Only update search page local state if it is not already equal

- src/IsaacAppTypes.tsx
- src/app/components/handlers/IsaacSpinner.tsx
- src/app/components/pages/MyGameboards.tsx
- src/app/components/pages/SetAssignments.tsx
- src/app/services/api.ts
- src/app/services/gameboards.tsx
- src/app/state/actions.tsx
- src/app/state/reducers/gameboardsState.ts
- src/app/state/selectors.tsx
- src/scss/common/boards.scss
- src/test/state/reducers.test.tsx
The primary goal of this was to make sure the "View more" button added new boards to the end of the list. That is solved by [this commit](https://github.com/isaacphysics/isaac-react-app/commit/4f4203499c8c8e82ac0a105f63000bfaf0dd475e).
I also made a couple of larger changes since the code for these components really needed a makeover:
---
A visual adjustment to `SetAssignments` and `MyGameboards` (see first commit), which makes the card view for both pages look much neater. James and Meurig approved of this change when demoing it to them.
---
The 6th commit pulls out the gameboard fetching logic for `MyGameboards` and `SetAssignments` into a hook defined in `gameboards.tsx`, and refactors the code in a few other ways:
- Gets rid of `actualBoardLimit` (this name confused me for about an …
> Gameboards "View more" incorrect ordering fix (and refactor)

- src/app/components/pages/Registration.tsx
- src/app/services/validation.ts
I've used placeholder text in the "ask your parents for consent" pop-up. 
There is another card about the proper wording of this pop-up, so this PR will have to wait for that to be figured out and copy-edited before being merged.
**It would still be useful for this to be reviewed**, so that the only thing left to do is work out the wording of the consent box.
> Allow registration for 10-12 year olds on physics

- src/app/components/elements/markup/markdownRendering.ts
- src/app/services/glossary.tsx
> Fix a bug where the display text of a [glossary-inline] term contains dashes

- src/app/components/content/IsaacClozeQuestion.tsx
This means that spaces left in cloze questions are persisted when passed between the frontend and API
> Add dummy "null item" to cloze choices

- src/IsaacApiTypes.tsx
- src/app/services/constants.ts
- src/app/services/userContext.ts
The backend change to support the new `year_7_and_8` tag has already been merged.
I have left in the old `year_7` and `year_8` tags and their labels for the time between the release and the content script swapping them all to use the new tag.
> Add Year 7/8 and 9 to dropdown options

- src/app/components/elements/inputs/UserContextAccountInput.tsx
- src/app/components/elements/modals/UserContextReconfirmationModal.tsx
- src/app/services/localStorage.ts
- src/app/state/middleware/notificationManager.ts
- src/app/state/middleware/utils.ts
- src/app/state/selectors.tsx
- src/test/services/notifications.test.ts
Modal will show to anyone who hasn't updated their user context details since the most recent 1st August.
**After final copyedit:**
Teacher relevant text on Phy:
Student relevant text on CS
> User context (stage, exam board, school) reconfirmation modal

- src/app/components/content/IsaacGraphSketcherQuestion.tsx
- src/app/components/elements/modals/GraphSketcherModal.tsx
Adds exposition text above the question and within the graph editor, and removes the duplicate row of hints.
> Show exposition text in Graph Sketcher, remove duplicate hints

- src/app/components/navigation/IsaacApp.tsx
- src/app/components/navigation/NavigationBar.tsx
- src/app/services/notificationChecker.ts
- src/app/services/websockets.ts
- src/app/state/actions.tsx
- src/app/state/reducers/userState.ts
On login success, the current user object is returned and so no further current_user requests are necessary. However, I think in order to avoid duplicating the logic for getting auth settings and preferences, we then dispatched a current_user request anyway.
This causes the Redux "user" object to change, even though its contents are identical, which causes many useEffects to fire unnecessarily. These unwanted firings caused many duplicate WebSocket requests, and duplicate auth/preference settings requests, which are bad for our server performance as much as the app performance.
After these changes, there's a bug with login. Previously, a login failure would have caused a pointless current_user request which would have reset the "user" state object back and removed the "requesting" …
> Prevent unnecessary user updates

- src/app/components/elements/modals/GameboardCreatedModal.tsx
- src/app/components/handlers/ShowLoadingQuery.tsx
- src/app/components/navigation/NavigationBar.tsx
- src/app/components/pages/Gameboard.tsx
- src/app/components/pages/GameboardBuilder.tsx
- src/app/services/miscUtils.ts
- src/app/services/navigation.ts
- src/app/state/slices/api/gameboards.ts
- src/app/state/slices/api/index.ts
This fixes the bugs found so far in regression testing the RTK query assignment and gameboard refactor, those being:
- Assignment progress cache isn't updated when new assignment is made
- Fast track navigation being "totally broken"
- Gameboard builder selecting random questions and breaking weirdly when "Create another gameboard" is clicked after creating one first
- "My assignments" and "My tests" counter overflowing to the next line
- Gameboard filter loading forever on filter combo without questions, instead of showing "No questions found..."
- Non-existent gameboard loading forever instead of displaying "Not found"
A couple of the fixes are a bit hacky, the patch to `isaacBaseQuery` in particular needing a revisit to fix the types - ideally, it should be clear from the RTK Query …
> Patch rtk query bugs

- src/IsaacAppTypes.tsx
- src/app/components/elements/panels/EventAttendance.tsx
- src/app/components/handlers/ShowLoadingQuery.tsx
- src/app/components/navigation/IsaacApp.tsx
- src/app/components/pages/AssignmentProgress.tsx
- src/app/components/pages/AssignmentSchedule.tsx
- src/app/components/pages/Gameboard.tsx
- src/app/services/assignments.ts
- src/app/services/constants.ts
- src/app/services/dates.ts
- src/app/services/index.ts
- src/app/services/miscUtils.ts
- src/app/state/slices/api/gameboards.ts
- src/scss/common/assignments.scss
- src/scss/common/icons.scss
- src/scss/cs/isaac.scss
- src/scss/phy/isaac.scss
This implements a new page to manage assignments based on their start and due dates. It's accessed via `/assignment_schedule`.
The idea is that this is released to live and anyone with the link can access it, and then we add it to the navbar later on. It is probably going to remain separate to the set assignments page since it represents a different part of the assignment workflow.
I have yet to add buttons to add gameboard from books and "boards for lessons", but this shouldn't hold back merging because the whole page is a hidden beta feature subject to change. There also isn't yet functionality to modify your current assignments - this can also be done later since it requires an API change (probably a new endpoint).
There are a couple of changes to gameboards and dates which are …
> Assignment Schedule

- src/IsaacApiTypes.tsx
- src/IsaacAppTypes.tsx
- src/app/components/content/IsaacClozeQuestion.tsx
- src/app/components/content/IsaacContent.tsx
- src/app/components/content/IsaacItemQuestion.tsx
- src/app/components/content/IsaacParsonsQuestion.tsx
- src/app/components/content/IsaacQuestion.tsx
- src/app/components/content/IsaacReorderQuestion.tsx
- src/app/components/content/QuizQuestion.tsx
- src/app/components/elements/inputs/ConfidenceQuestions.tsx
- src/app/components/elements/markup/portals/InlineDropZones.tsx
- src/app/services/api.ts
- src/app/services/questions.ts
- src/app/state/actions/index.tsx
- src/app/state/reducers/quizState.ts
This threads the type change through the codebase. I didn't thread it through the `IsaacContent` component or anything related because it would be a huge faff, instead opting to cast immutable `ContentDTO`s to mutable ones where appropriate.
In the process, I fixed some potential state mutations in Parsons and reorder questions.
> Mark current question attempts as immutable

- src/app/components/handlers/AddGameboard.tsx
- src/app/components/pages/AssignmentSchedule.tsx
- src/app/components/pages/Gameboard.tsx
- src/app/components/pages/GameboardFilter.tsx
- src/app/components/pages/SetAssignments.tsx
- src/app/services/localStorage.ts
- src/app/state/actions/index.tsx
- src/app/state/slices/api/gameboards.ts
Requires redirecting user back to assignment setting page they originally pressed these buttons from - I save the path to redirect to in local storage and default to `/set_assignments` if it is missing. 
It won't (shouldn't) be possible for a user to accidentally be redirected to the assignment schedule unless they've visited it already in that session and take a weird path through the app.
> Add book board and gameboard builder buttons to assignment schedule

- src/app/components/handlers/ExternalRedirect.tsx
- src/app/components/navigation/IsaacApp.tsx
- src/app/components/pages/LogIn.tsx
- src/app/services/localStorage.ts
- src/app/state/actions/index.tsx
This implements a general way to add external redirects to the site, and uses this pattern to add a redirect to Qualtrics survey pages via `/survey/:qId` where `qId` is the survey id.
Additionally, this refactors a couple of small things, and fixes a weird race condition involving the after auth redirect logic. You might want to review this with whitespace turned off: `?w=1`.
> Qualtrics survey redirect

- src/app/components/pages/Glossary.tsx
CS isn't using exam boards anymore for glossary terms so this removes the filtering logic from /glossary
> Remove examBoard from Glossary.tsx filtering logic

- package.json
- yarn.lock
Fixes matrix determinant rendering issues: `/concepts/cm_matrices_determinants` is a great example page to compare before and after.
Having read the changelogs for the [recent KaTeX releases](https://github.com/KaTeX/KaTeX/releases) it doesn't look like there are any breaking changes for us.
> Upgrade KaTeX to 0.16.2

- src/app/components/elements/modals/inequality/utils.ts
This avoids the case where you couldn't have `Delta`, `delta`, and `d` as individual letters instead of differentials without argument.
> Avoid capturing Delta, delta, and d as differentials if they aren't followed by variables

- src/app/components/content/IsaacCodeSnippet.tsx
I pushed the addition of the new log type in the API straight to master (it was just adding another value to an enum)
> Log "view github code" event when that button is clicked on code snippets

- src/app/components/content/IsaacParsonsQuestion.tsx
Just a case of re-registering mouse/key event listeners when their deps change, and unregistering old ones.
This also fixes the issue of the current attempt not updating when indentation is changed (but I'm not 100% certain why)
> Fix Parsons indentation using mouse drag

- src/app/components/pages/AssignmentSchedule.tsx
- src/app/components/pages/SetAssignments.tsx
- src/app/services/dates.ts
- src/app/state/slices/api/gameboards.ts
By rounding down the scheduled start date to the nearest day in order to perform the comparison.
Should be merged with [the related API PR](https://github.com/isaacphysics/isaac-api/pull/496).
> Allow assignments to be scheduled on the same date as they are due

- src/IsaacAppTypes.tsx
- src/app/services/quiz.ts
- src/app/state/actions/index.tsx
- src/app/state/middleware/hidePreviousQuestionAttempt.ts
The "hide previous answers" beta feature misbehaves with quiz questions, making them unanswerable. This PR makes quiz questions ignore the setting.
> Ignore 'hide previous answers' setting for tests

- src/app/components/content/IsaacNumericQuestion.tsx
- src/app/components/elements/markup/portals/InlineDropZones.tsx
- src/scss/common/questions.scss
This implements the preferred item-by-item feedback styling (decided by physics) for cloze questions and numeric questions.
The idea is to keep this style for other question types that need this kind of feedback going forwards, so that the user message is consistent.
> Item-by-item feedback style

- src/app/components/pages/GameboardFilter.tsx
Fixed by not unsubscribing from the gameboard-fetching promise. I can't believe I missed this before... it doesn't look like this causes a ridiculous number of boards to be stored in Redux, so we can just remove the `unsubscribe` call.
> Fix question finder loading infinitely on shuffle and reload

- public/index-cs.html
- public/index-phy.html
- src/app/components/content/IsaacClozeQuestion.tsx
- src/scss/common/isaac.scss
There is an easy fix on newer browsers which consists of setting `overflow: clip` for the root div on both sites.
For all other browsers, we need to set `scrollLeft = 0` whenever the root div tries to scroll. This plays nicely with the fix for newer browsers and is fairly lightweight and self-contained. 
If the browser doesn't have `overflow: clip` support, there is a small discrepancy between where an item is dropped and where its drop animation indicates it will be dropped, but this only happens where the bug would occur previously and is a big improvement.
> Stop cloze item dropping into off-screen drop-zone causing entire screen to offset

- src/app/components/elements/quiz/QuizAttemptFooter.tsx
- src/app/components/pages/quizzes/QuizAttemptFeedback.tsx
- src/app/components/pages/quizzes/QuizDoAssignment.tsx
- src/app/components/pages/quizzes/QuizDoFreeAttempt.tsx
- src/app/services/quiz.ts
- src/scss/phy/isaac.scss
This makes the buttons etc. in the test attempt pages use the subject colour of the test. 
It defaults to physics if no subject tag is present - the subject tag needs to be added at the quiz DTO level.
As a side effect, this PR stops Physics UI elements from using the `phy_extra_force_yellow` colour, and makes them use `a11y_green` instead.
> Use subject colour in test page UI

- src/app/components/pages/SetAssignments.tsx
And only try to open it once per new hash anchor.
This fixes the issue with the modal opening again if you change the view of the gameboards. 
This is because changing the view causes the gameboards to be fetched again, which unmounts and remounts each `Board` component. The "open modal if hash anchor matches this board" logic was inside `Board` and ran on component mount, and we didn't have a nice way to work out whether a given mount was the first time the board had been loaded. 
This fix future-proofs the code a fair bit - we had one modal component per gameboard beforehand which could easily go wrong (multiple modals open at once for example) if the code was changed slightly.
**It looks like a lot of lines changed, but it is mostly just moving large-ish completely separate blocks of …
> Move assignments modal to top level `SetAssignments` component

- src/app/components/elements/inputs/UserContextAccountInput.tsx
- src/app/components/elements/modals/RequiredAccountInformationModal.tsx
- src/app/components/elements/panels/UserDetails.tsx
- src/app/components/navigation/IsaacApp.tsx
- src/app/components/navigation/TrackedRoute.tsx
- src/app/components/pages/TutorFeatures.tsx
- src/app/components/pages/TutorRequest.tsx
- src/app/components/site/phy/NavigationBarPhy.tsx
- src/test/pages/IsaacApp.test.tsx
- src/test/pages/authorisationRedirects.test.ts
This does the following:
* Remove intermediate (are you teacher or tutor?) page
* Make "explain" a required field in the Tutor form
* In Tutor features, replace Teacher FAQ with greyed-out Tutor FAQ
* In Help, replace Teacher FAQ with greyed-out Tutor FAQ
We need to link to the tutor form page in text in `/pages/contact-us-teacher` (this is a content change and I believe content are on it)
> Tutor pre-release changes

- src/app/components/elements/Accordion.tsx
- src/app/components/elements/panels/AddUsersToBooking.tsx
- src/app/components/elements/panels/EventAttendance.tsx
- src/app/components/elements/panels/SelectedEventDetails.tsx
Extends `Accordion` with a `disabled` attribute, that de-emphasises it and stops it from being opened.
This is used to disable the event admin page accordions for:
- Booking users onto events
- Promoting reserved users to booked
for events that have been cancelled.
This is for UX purposes: if they were to use these accordions in any capacity after [this back-end PR](https://github.com/isaacphysics/isaac-api/pull/493) goes in, they'll just get server errors.
> Stop admins from booking users onto cancelled events

- src/app/components/pages/quizzes/QuizDoAssignment.tsx
- src/app/components/pages/quizzes/QuizDoFreeAttempt.tsx
- src/app/services/quiz.ts
I believe this fixes the issue. It's hard/impossible to test this edge case as it has only turned up a few times in the server logs on live AFAIK, so I suggest we merge this and see whether any further errors turn up in the logs afterward. This is fine since the change is small and completely sensical.
The problem was in `useCurrentQuizAttempt`. The `attempt` object it returned was **always defined** because it augments the original attempt with the document subject: 
```typescript
const attemptWithQuizSubject = {...attempt, quiz: attempt?.quiz && tags.augmentDocWithSubject(attempt.quiz)}
...
return {attempt: attemptWithQuizSubject, error, studentUser, questions, sections};
```
The main reason this broke things is in `QuizDoFreeAttempt` and `QuizDoAssignment`:
```jsx
<ShowLoading …
```
> Fix `undefined` quiz attempt id errors

- package.json
- src/app/components/content/IsaacVideo.tsx
- src/app/components/navigation/IsaacApp.tsx
- src/app/components/navigation/TrackedRoute.tsx
- src/app/components/pages/ClientError.tsx
- src/app/components/pages/Registration.tsx
- src/app/components/pages/ServerError.tsx
- src/app/components/pages/SessionExpired.tsx
- src/app/services/constants.ts
- src/app/state/actions/index.tsx
- src/app/state/actions/popups.ts
- yarn.lock
This just runs both versions of ReactGA alongside one another. 
The new version is a bit crusty but does the job fine (it's essentially just a light wrapper around `gtag.js`) - by this I mean the convenience methods `pageview` and `exception` now no longer exist but you can just use the base `gtag` method to send GA the same message.
I've created a GA4 "property" for each site - the measurement ids in this PR are not placeholders.
> Run Google Analytics 4 alongside current Universal Analytics

- src/app/components/elements/inputs/DateInput.tsx
- src/app/components/elements/inputs/DobInput.tsx
- src/app/components/elements/modals/QuizSettingModal.tsx
- src/app/components/pages/AssignmentSchedule.tsx
- src/app/components/pages/SetAssignments.tsx
- src/app/components/pages/quizzes/QuizTeacherFeedback.tsx
New behaviour: 
- If the day is 09/12/2023 and you input 5 as the day, the date input defaults to 05/01/2024
- If the day is 09/05/2023 and you input 5 as the day, the date input defaults to 05/06/2023
- If the day is 01/09/2023 and you input 5 as the month, the date input defaults to --/05/2024
This was harder than we thought! IMO we need a new date input method (I actually have a "nicer" one in a branch somewhere) because rolling your own is tricky.
Would benefit from someone testing it again locally
> Wrap month and year properly when setting day in date inputs

- src/IsaacApiTypes.tsx
- src/IsaacAppTypes.tsx
- src/app/components/elements/modals/ReservationsModal.tsx
- src/app/components/pages/EventDetails.tsx
- src/app/services/events.tsx
- src/test/services/events.test.tsx
Needs copy.
---
The `RESERVED_ONLY` event status displays the following for students:
and makes no difference to the teacher view. An event that is both `RESERVED_ONLY` but not group booking doesn't make any sense, but I haven't handled this case because it's fundamentally a content error (and a by-product of the overcomplicated way we categorise events)
> Add group event booking contact form to manage group reservations modal

- src/app/components/pages/Concept.tsx
- src/app/components/pages/Generic.tsx
- src/app/components/pages/Question.tsx
- src/scss/phy/isaac.scss
I decided to try and impact the style of the site less by using the same grey background colour, instead of white. This way, we also don't need to handle pages with cards any differently, since the background change is subtle.
It uses `box-shadow` to fade into the background graphic nicely, which has been supported on all browsers for a long time.
`/concepts/cm_roots_of_polynomials` is a good page to compare before and after:
Before:
After:
> Make sure that text isn't obscured by background graphics

- src/app/services/api.ts
- src/app/services/constants.ts
In cases where the image path contains an API version number, then images from the content cannot be cached for long since the version number changes each release.
This instead uses a new route that gives the images a URL which does not change from release to release, added in: https://github.com/isaacphysics/isaac-router/commit/b0fb97aaf5cae95012c91d916c7696cb8b17dd3e
> Use new path for long-term caching of content images

- src/app/components/pages/Groups.tsx
- src/test/pages/Groups.test.tsx
Adds additional managers to the group overview, and moves buttons around to be more intuitive.
See pics for the (medium/large screen) layouts on Ada and physics - it is nicely responsive on small screens.
> Redesign manage groups UI

- src/IsaacAppTypes.tsx
- src/app/components/pages/AssignmentProgress.tsx
- src/app/components/pages/SingleAssignmentProgress.tsx
- src/app/services/gameboardBuilder.ts
- src/app/services/sorting.ts
- src/app/state/slices/api/assignments.ts
Default sorting is now "start date descending", start date meaning the scheduled start date (if it exists - it is the creation date if not). 
Ascending and descending options exist for due date, start date, and title.
Isaac Physics:
Ada CS:
> Add assignment sorting dropdown to top of markbook/assignment progress page

- src/app/components/elements/modals/QuestionSearchModal.tsx
On the Gameboard Builder page, we were defaulting to ordering question query results by difficulty in the front-end.
This overrode ElasticSearch's relevance ranking returned by the back-end service and caused odd behaviour like a question being ranked lower as more exact-match words were added to the query (i.e. try searching for the question with title "Combinatronics with isotopes" on the old version of the site).
This PR also clears any front-end sorting of results on re-querying the back-end service so that the default ranking is always by ElasticSearch's relevance score.
> Stop overriding ES ranking in gameboard builder front-end

- src/app/components/elements/quiz/QuizAttemptComponent.tsx
- src/app/components/elements/quiz/QuizProgressCommon.tsx
- src/app/components/pages/quizzes/QuizAttemptFeedback.tsx
- src/app/services/constants.ts
- src/scss/common/quiz.scss
For tests created after a specified date - this should be modified before the release.
Also modifies the student name buttons on quiz feedback a little (hence the SCSS changes and some JSX refactoring).
---
The text shown to students when attempting a test assignment will need to be updated based on the copy given by the content team.
> Allow teachers to view students test answers

- src/app/components/elements/quiz/QuizAttemptComponent.tsx
- src/app/components/elements/quiz/QuizAttemptFooter.tsx
- src/app/components/pages/quizzes/QuizDoAssignment.tsx
- src/app/components/pages/quizzes/QuizDoFreeAttempt.tsx
- src/app/services/tagsAbstract.ts
- src/app/services/tagsCS.ts
- src/app/services/tagsPhy.ts
The generifying of `augmentDocWithSubject` was necessary for the types to work out in some other code to do with this PR - I removed that code (it was wrong) but kept the extra typing because it improves type inference and autocompletion if you're working with objects that have passed through that function. Beforehand, calling `augmentDocWithSubject(obj)` erases the type of `obj` to `ContentDTO & {subjectId: string}` (if `obj` is of type `QuizDTO` for example then this is annoying).
> Redirect users to feedback page (if allowed) after quiz submission

- src/app/components/content/IsaacSymbolicLogicQuestion.tsx
- src/app/components/content/IsaacSymbolicQuestion.tsx
- src/app/components/pages/Equality.tsx
There was previously an issue in the inequality modal where multiple instances of p5 hung around sometimes - I'd already fixed it using this same pattern.
I _think_ that doing the same thing for the other mini instances of inequality (used to parse text input outside of the modal) will fix the strange "massive invisible p5 canvas at the top of the page" issue.
Even though those mini instances are created with `textEntry: true`, the canvas elements (that are given an initial height of 0px) associated with them **are still resized as if they were full-screen if the window size changes**. I have a hunch that this is the cause of (or is closely related to) the problem.
> Explicitly cleanup p5 on component unmount

- src/IsaacApiTypes.tsx
- src/app/components/elements/modals/QuizSettingModal.tsx
- src/app/components/pages/quizzes/QuizTeacherFeedback.tsx
- src/app/components/pages/quizzes/SetQuizzes.tsx
- src/app/state/actions/quizzes.tsx
And display this information on "manage tests" and "test feedback" pages.
Feature is only available for staff users currently.
> Add ability to set scheduled start date for quizzes (tests)

- src/app/components/pages/AssignmentSchedule.tsx
- src/app/components/pages/SetAssignments.tsx
- src/app/state/slices/api/gameboards.ts
- src/scss/common/assignments.scss
If you switch from start date to due date view or visa versa, sometimes the earliest show date needs to be brought back in order for any assignments to be shown. This implements that.
> Assignment schedule: improve assignment filtering by date when switching between views

- src/app/components/pages/AssignmentSchedule.tsx
- src/app/services/gameboards.tsx
- src/scss/common/assignments.scss
- src/test/pages/MyGameboards.test.tsx
All of this extra info is hidden unless "Show more" is clicked.
The extra info is hidden once the card is hidden, which keeps the view compact unless the user explicitly wants to see more details.
Collapsed:
Expanded:
> Add assignment notes and gameboard info to assignment schedule cards

- src/IsaacApiTypes.tsx
- src/app/components/content/IsaacInteractiveCodeSnippet.tsx
- src/mocks/data.ts
- src/test/pages/UserContextReconfirmationModal.test.tsx
- src/test/setupTests.ts
_The failing test has nothing to do with this_
Commit message "Set mock user registeredContextsLastConfirmed to -1 days in the future" should say "... -1 day in the past" - not too worried because the diff and extended commit message make it clear what the change was
> Pass dataUrl through to code editor in interactive code snippet

- src/app/components/elements/markup/latexRendering.ts
This is difficult. The sr-only class does not stop the contents from appearing on the clipboard, which is a different sort of accessibility violation in itself, because it makes the pasted text (e.g. for conversion into Braille or to be used elsewhere) confusing.
The obvious fix is to replace the span text with an aria-label. But aria-label is prohibited on non-interactive content like spans: https://w3c.github.io/aria/#aria-label
To fix this, we can add an aria-role to the KaTeX element. The obvious one is role="math". This works fine for NVDA on Chrome/Firefox but breaks VoiceOver because that just states "maths" and ignores the label. Breaking VoiceOver is a no-go, since that is basically the main option on MacOS and iOS.
Fortunately, most browsers and screenreaders ignore the ARIA …
> Prevent doubling of copy-pasted maths keeping A11Y

- compose
- compose-live
Necessary for https://github.com/isaacphysics/isaac-api/pull/552 to work on the servers; adds the MaxMind database file into the Docker containers.
> Add MaxMind IP location database to Docker volumes

- src/app/components/pages/AssignmentProgress.tsx
- src/app/state/slices/api/assignments.ts
For tutors we were requesting their tests on the Assignment Progress page even though they cannot set test and this was resulting in an error toast being displayed on each visit.
Using a `skipToken` is the idiomatic way of conditionally querying an endpoint (`skipToken` preferred over `{skip: true}` options for easier typing): https://redux-toolkit.js.org/rtk-query/usage/conditional-fetching.
> Skip queries for set Tests if user is tutor

- src/app/components/pages/Groups.tsx
- src/test/pages/Groups.test.tsx
If there are no managers to remove, change 'Add / remove group managers' text to just 'Add group managers'.
> Update button text for adding group managers

- src/app/components/pages/Groups.tsx
Will warn the user if they enter a group name when creating a new group or editing an existing one that already exists; this does not block them from adding it should they insist.
> Warn on duplicate group name

- src/app/components/content/IsaacGraphSketcherQuestion.tsx
- src/app/components/pages/GraphSketcher.tsx
- src/scss/common/graph-sketcher-modal.scss
Adds instructional text beneath the graph sketcher, as requested by the content team, for ease of use. The text does not display when printing.
> Instructional text for graph sketcher

- src/app/services/constants.ts
- src/app/services/tagsPhy.ts
Apply content team's requested changes: support for 'polymers' content tag, rename 'Bonding' topic to 'Bonding & IMF'.
> Add Polymers polygon, rename Bonding polygon

- src/app/components/content/IsaacClozeQuestion.tsx
When dragging, boxes that visually overlap should have priority for drop location.
> Prioritise overlapping boxes in cloze drag & drop

- src/app/components/pages/Groups.tsx
On the group management page, compress the 'Reset Password' and 'Remove [member]' buttons into a dropdown on xs resolutions.
> Add dropdown for managing group members on small devices

- src/app/components/elements/svg/HexagonConnection.tsx
- src/app/components/elements/svg/HierarchyFilter.tsx
- src/app/components/pages/GameboardFilter.tsx
Stops hexagons from clipping off the edge of the screen for very small devices (min supported width now 343px).
> Prevent question select clipping on tiny devices

- src/app/components/elements/modals/GroupsModalCreators.tsx
Clearer wording about the inability for demoted owners to add or remove managers (which they previously could do).
The warning dialogue about converting a manager to an owner distinguishes between whether the privileges are allowed or not.
> Reword additional managers and ownership change dialogue

- src/app/components/navigation/IsaacApp.tsx
- src/app/components/site/ScrollToTop.tsx
- src/scss/common/scroll-button.scss
- src/scss/cs/isaac.scss
- src/scss/phy/isaac.scss
ScrollToTop component added to the IsaacApp component. It remains at the bottom of the screen (out of site) until the user scrolls beyond the top of the main content at which point it sticks to the bottom right of the screen.
Currently only on the Ada site but removing the conditional will add it to the Physics site as well. The scroll-button.scss will also need to be imported in the relevant isaac.scss file.
> Add scroll-to-top button

- src/app/components/content/IsaacCard.tsx
Adding the title of the resource card as an aria-label for both the clickable links and Link components in the resource cards.
> Improve screenreader descriptions for resource cards

- src/app/components/elements/svg/DifficultyIcons.tsx
Adding the "img" role to the DifficultyIcons svg means the title will be read out. hiding the individual 'P'/'C's means that only the difficulty with be read out.
> Add screenreader descriptions for question difficulty

- src/IsaacApiTypes.tsx
- src/app/components/elements/GameboardBuilderRow.tsx
- src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
- src/app/components/pages/Gameboard.tsx
- src/app/components/pages/Question.tsx
Displays a question's subtitle in various places. In search, hides when a summary is present.
(requires API change: https://github.com/isaacphysics/isaac-api/pull/561)
> Show subtitles in search, question pages, and gameboard viewer

- src/app/services/constants.ts
- src/app/services/tagsPhy.ts
Adding "coordinates" to the TAG_ID and tagsPhy under math > geometry > coordinates
> Add "coordinates" to tags for question finder

- src/app/components/elements/Assignments.tsx
The card title text was overflowing for long strings with no soft breaks.
> My Assignments card text overflow

- src/app/components/elements/cards/BoardCard.tsx
In the My Gameboards table the completion div graphic is added to the screenreader tab sequence. This has not been added to assignments, tests, etc.
> Prevent screenreaders skipping gameboard completion column

- src/app/components/elements/Accordion.tsx
- src/scss/common/accordions.scss
- src/scss/cs/accordions.scss
- src/scss/cs/isaac.scss
Wrap the accordion title spans in H2 headers. 
Additional styling to revert to the previous style still required if desired.
> Convert accordion titles to H2 headers

- src/IsaacAppTypes.tsx
- src/app/services/searchResults.ts
Also adds some terms and fixes some ESLint warnings.
The new type was to ensure that I could append the site specific lists onto the main list without type errors, since the currently-empty Ada list caused issues.
> Split search shortcuts into site specific groups

- src/scss/cs/accordions.scss
With the updated headers in Ada content accordions H3 titles will be underlined (the largest title in a content accordion) and H4 titles (nested underneath H3) are not.
Note that the accordion title and internal headers all have the same style now (that is the old accordion title <span>).
> New Ada content headers

- src/app/components/elements/cards/NewsCard.tsx
The read more link now includes the title of the news pod when tab focused as the title is otherwise not read out.
> Add aria-label to news pod read more link

- src/app/components/pages/quizzes/SetQuizzes.tsx
- src/scss/common/quiz.scss
- src/scss/phy/isaac.scss
- src/scss/phy/quiz.scss
Adds title, group, and date filtering to the Manage Tests page.
Ideally once the ability to set tests to multiple groups at once is in place, cards in this page could be grouped in a similar way.
> Add filters to the "Manage Tests" page

- src/app/components/elements/modals/QuizSettingModal.tsx
- src/app/services/quiz.ts
- src/app/state/slices/api/quizApi.ts
Relies on [Test setting to multiple groups #564](https://github.com/isaacphysics/isaac-api/pull/564) in the backend as it anticipates the new POST and return types.
Single quiz assignments are still possible by selecting only one group.
> Test setting to multiple groups

- src/app/components/elements/views/QuestionProgressCharts.tsx
The charts are now hidden from screen readers with a visually hidden table for the screenreaders. This table can later be made visible if desired.
Additional changes to comply with ESLint.
> Add screenreader only tables for "My progress" charts

- package.json
- src/app/components/elements/modals/GraphSketcherModal.tsx
- yarn.lock
Converts to the old [0] / [1] indexing for Graph Sketcher Points for easier use with the backend.
Requires the equivalent sketcher PR to provide the functionality.
> Sketcher: consistent point representation for backend endpoint

- src/app/components/elements/modals/GraphSketcherModal.tsx
- src/app/services/device.ts
- src/scss/common/graph-sketcher-modal.scss
Adds a new useDeviceHeight hook to permit proper layout in the sketcher when in landscape mode.
> Prevent button overlaps in sketcher UI

- src/scss/common/forms.scss
The DateInput element has removed some ReactStrap-default properties but keeping others, making the overall element look a little off, particularly when invalid.
> Fix date input element size and borders

- src/app/components/site/ScrollToTop.tsx
- src/scss/common/print.scss
- Unsets min-width when printing so the Scale parameter in print menus works as intended;
- Since the previous print layout was designed for 992px min-width, sets the page size to this plus the padding difference not added by @ page size (0.5in left/right/top/bottom).
This correction isn't perfect, and the scale of certain pages is very slightly different to before. Worth checking if this affects any pages in particular.
> Print at scale without overflowing

- src/app/components/pages/SetAssignments.tsx
- src/app/services/quiz.ts
- src/app/state/slices/api/gameboards.ts
When setting an assignment or quiz checks on whether the due date is valid is done in the modal, the redux thunk, and
the backend. This is inefficient, so the redux thunk checks have been removed.
- Add front end date checks to set assignment
- Remove unnecessary redux date checks
> Remove unnecessary redux checks

- src/app/components/elements/modals/GraphSketcherModal.tsx
The \<button\>s were causing the top-level form to submit, i.e. submitting the question attempt. Replacing these with divs with the button role prevents this.
> Replace sketcher UI buttons with divs

- src/app/components/elements/markup/index.tsx
- src/app/components/elements/markup/portals/GlossaryTerms.tsx
- src/scss/common/glossary.scss
Removes all text styling from glossary terms when they are inside another inline glossary term's definition. Does **not** remove this styling if the parent glossary term is displayed as a block, e.g. in the bottom glossary.
> Remove text styling from terms in inline definition

- src/app/components/elements/modals/QuizSettingModal.tsx
- src/app/components/pages/quizzes/SetQuizzes.tsx
- src/app/state/actions/quizzes.tsx
Previously only staff members could set start dates for tests. This
functionality has been extended to user accounts, this only applies to
accounts that can set tests.
> Allow users to set start dates for tests

- src/app/components/pages/Generic.tsx
When linking to a page with a hash anchor, if the content is loaded asynchronously the browser can attempt to jump to the hash location before it is loaded. The original solution to this was to trigger a rescroll to the hash once the content was loaded, but this inadvertantly added to the browser stack and thus occasionally broke the browser history stack buttons.
> Fix hash links to accordions breaking browser stack

- src/app/state/actions/index.tsx
The dispatch allows the rest of the site to load as if they were logged in, and we can later infer that we should redirect to the verify page if they try to do something that requires a ("full", i.e. verified) account as the session cookie notes that the verification is incomplete.
> Redirect to /verify on unverified teacher login

- src/app/components/content/IsaacQuestion.tsx
- src/app/components/navigation/IsaacApp.tsx
- src/app/components/navigation/NavigationBar.tsx
- src/app/components/navigation/TrackedRoute.tsx
- src/app/services/user.ts
- src/app/state/actions/index.tsx
Modifies TrackedRoute such that, for Ada teachers only, if they are accessing a page that requires an account and are not verified, they are redirected to the verification page.
Also adds verification checks to question attempts, navigation bar requests (e.g. indicator of num. of tests set), and other user requests to prevent warning toasts.
> Redirect to /verify when account required in partial login

- src/app/components/content/IsaacSymbolicQuestion.tsx
When a user changes their input the response banner needs to be removed
to allow the user to reassess their attempt. This is done through
`dispatchSetCurrentAttempt` which sets `validationResponse` to
`undefined`.
The issue with symbolic questions is that there are two input types that
need to be kept in sync and both need to be able to set a current
attempt. Text input only does this when there is no input otherwise it
updates symbolic input's state. The symbolic input will always run the
dispatch when it's state changes.
However, the symbolic input's state is set on reload which triggered the
dispatch causing the brief flash of the banner. Adding conditions to
make sure that there has been a meaningful change prevents this.
> Prevent symbolic question response resetting on reload

- src/app/components/elements/EventBookingForm.tsx
When an event only includes teachers use "Role" rather than "School year group" to align with the options available.
> Use "Role" for teacher event booking detail input

- src/app/components/elements/inputs/CheckboxInput.tsx
- src/app/components/elements/inputs/UserEmailPreferencesInput.tsx
- src/app/components/elements/panels/MyAccountTab.tsx
- src/app/components/elements/panels/TeacherConnections.tsx
- src/app/components/elements/panels/UserBetaFeatures.tsx
- src/app/components/elements/panels/UserDetails.tsx
- src/app/components/elements/panels/UserEmailPreferencesPanel.tsx
- src/app/components/elements/panels/UserMFA.tsx
- src/app/components/elements/panels/UserPassword.tsx
Various changes to the existing sign-up flow to improve the styling for both sites.
Ada:
- Adds the required changes to the Beta Features tab
Phy:
- Brought back the notifications table with radio buttons
Both:
- Improved tab styling on small devices
- Abstracted the tab container into a new component, MyAccountTab, which contains the styling for both sites
- If (when) physics want the redesign changes, funnel through the Ada part of this component.
> Improve existing styling, bring back phy notification table

- src/app/components/pages/quizzes/SetQuizzes.tsx
Uses the assignment set to one specific group, rather than the generic assignment used earlier in the code.
> Fix incorrectly disabled "Extend due date" button on tests

- src/app/components/elements/quiz/QuizProgressCommon.tsx
Changing the conditional on the due date so that if a due date does not exist the 'Allow another attempt' button is
still shown.
> Fix 'Allow another attempt' button visibility

- src/app/components/elements/cards/BoardCard.tsx
- src/app/components/pages/MyGameboards.tsx
- src/app/components/pages/SetAssignments.tsx
- src/scss/common/boards.scss
In `/set_assignments` and `/my_gameboards`, display the Stages and Difficulties tabs as one extended table, with separating lines for easier viewing. 
To make space for this, the Creator column (which may be removed later regardless) has been moved under the Quiz Name, and the Share button has been removed given its functionality is entirely replicable simply by clicking the quiz name. 
All changes affect physics only. Ada remains unchanged.
> Display Stages and Difficulties as table

- src/app/components/pages/AssignmentProgress.tsx
- src/app/components/pages/GameboardBuilder.tsx
- src/app/components/pages/GameboardFilter.tsx
- src/app/components/pages/Groups.tsx
- src/app/components/pages/MyAssignments.tsx
- src/app/components/pages/SetAssignments.tsx
- src/app/components/pages/books/chemistry_16.tsx
- src/app/components/pages/books/phys_book_gcse.tsx
- src/app/components/pages/books/physics_skills_19.tsx
- src/app/components/pages/books/pre_uni_maths.tsx
Currently leaves all Ada content alone, they do not use modals so are not following the updated format.
> Use updated content IDs for toptext and modals

- src/app/components/content/IsaacSymbolicQuestion.tsx
This change will always allow *all* Greek letters, despite Inequality only converting a subset of these to their textual equivalents; this does technically mean that A and capital-alpha will be treated as different variables. However, since no question uses these symbols (or, where they do, they use the Latin-script equivalent) this will only be an issue if someone copy-pastes the symbols in from elsewhere.
> Allow Greek symbols in symbolic question regex

- src/app/components/elements/Accordion.tsx
- src/app/components/elements/list-groups/TopicSummaryLinks.tsx
- src/app/services/constants.ts
- src/app/services/userContext.ts
- src/scss/common/accordions.scss
- src/scss/common/topic.scss
- src/scss/cs/accordions.scss
- src/scss/cs/isaac.scss
- Remove "all stages" from Ada, show comma-separated (but no commas between lines) list of all applicable stages
- Reuse GCSE/A Level colours for N5 / Adv Higher, use dark pink for Higher
- Minor styling changes to fit above changes in accordions, remove accordion-h3 underline.
> Ada accordion adjustments

- src/app/components/pages/Contact.tsx
- src/app/components/pages/NotFound.tsx
This brings Phy and CS into alignment, except on the breadcrumb title where the CS value of "404" remains.
> Add link from 404 page to contact form preset

- src/app/components/elements/RelatedContent.tsx
- src/app/services/userContext.ts
Ada wants a more strict check that enforces a stage and examboard to be present on a question (or item of content) for it to be considered on a user's specification.
This means that the `isIntendedAudience` needs to fail early rather than ignore stage and examboard. This is really a different function entirely and we don't necessarily want all uses of `isIntendedAudience` to behave like this on Ada. This should be changed in future after the release and the two functions used appropriately.
> Change Ada isIntendedAudience to behave like isOnSpecification

- src/app/components/pages/GameboardBuilder.tsx
The button used to be inside the scroll region, which meant on smaller screens it was hidden from view, especially on Safari where scrollbars are not shown to the user.
There are no functionality changes, only layout changes.
This might be easiest to review ignoring whitespace!
> Move add more button outside board builder table

- src/app/components/content/IsaacNumericQuestion.tsx
- src/scss/common/questions.scss
Decouples numeric questions' unit box from the fixed grid sizes previously imposed to allow auto resizing based on the content. Keeps the previous min-width of 192px in place; will only expand from this if necessary.
> Stretch numeric question's unit box to fit long units

- src/app/components/elements/inputs/UserContextPicker.tsx
If only one board exists for a given stage, select it by default and hide "All Exam Boards" from the dropdown.
> Select specific board over All if only one choice

- src/app/components/elements/RelatedContent.tsx
- src/app/services/userContext.ts
If a related question only has a stage (no examboard) it will be
considered "off specification" regardless of what examboard the
user has.
Furthermore, if there are related questions they will always be
displayed regardless of whether any are "on you specification".
> Show related questions without examboard as off specification

- src/app/components/content/IsaacClozeQuestion.tsx
`window.scrollBy` seems to move elements in the DOM around incorrectly on Safari -- they appear visually in the correct place, but inspecting them shows the layout boxes do not line up with these visuals. This solves itself if you scroll even a tiny bit, but if you don't, all the dnd fields are offset. 
Seemingly `window.scrollTo` is not subject to the same curse, so this replaces scrollBy with its equivalent scrollTo.
> Safari Cloze DND fix

- src/app/components/elements/AccountTypeMessage.tsx
- src/app/components/elements/inputs/UserContextAccountInput.tsx
- src/app/components/elements/modals/RequiredAccountInformationModal.tsx
- src/app/components/elements/panels/UserProfile.tsx
- src/app/services/constants.ts
Annoyingly the Ada designers want bolded links, which means a bunch of siteSpecifics. Ideas welcome on how to fix this/make it nicer!
Also remove the existing text next to the context picker since it was only shown to students but only helpful to teachers. 
Role names are now lowercase, but these are only used by the AccountTypeMessage component anyhow.
> Restore prominent upgrade role link to My Account

- src/app/components/elements/Accordion.tsx
- src/app/components/elements/list-groups/TopicSummaryLinks.tsx
- src/scss/common/accordions.scss
- src/scss/common/topic.scss
On mobile only, replaces comma-separated stage names with newlines to allow more horizontal space for accordion titles and the dropdown indicator.
> Mobile: more space for accordion title and indicator

- src/app/components/elements/inputs/UserContextPicker.tsx
- src/app/components/pages/Concept.tsx
- src/app/components/pages/Search.tsx
- src/app/components/pages/Topic.tsx
- src/scss/common/pages.scss
- src/scss/common/search.scss
- src/scss/cs/pages.scss
Adds a context picker for physics search, allowing a workaround for issues with only the first context being displayed. Also restructures the code to hugely simplify both how the UserContextPicker is used and the produced DOM by preferring the typical Bootstrap-style format.
Note for reviewer, the context picker is (now) used in 3 places on both sites:
- search
- concept pages
- topic summary pages
> Context Picker on Physics Search, layout improvements

- src/IsaacApiTypes.tsx
- src/app/components/elements/modals/TeacherConnectionModalCreators.tsx
- src/app/components/elements/panels/TeacherConnections.tsx
- src/app/components/pages/Groups.tsx
- src/app/state/slices/api/groupsApi.ts
- src/scss/common/groups.scss
Allows self-removal from groups for which this is enabled. This can be set via a new checkbox on the Manage Groups page.
> Add ability for student self-removal from groups

- src/app/components/pages/Events.tsx
- src/app/services/constants.ts
- src/app/state/slices/api/eventsApi.ts
Replaces the "Year 7&8" and "Year 9" filters with one combined "Years 7, 8 & 9" filter for both.
I'd have liked to incorporate `getFilteredStageOptions` here rather than define a new `EventStageMap` for consistency with elsewhere, but we need instead to define an overrides list to apply the replacement to the result. This works but is overcomplicated and less extensible so I have returned to using a separate constant.
> Combine KS3 events filters into "Years 7, 8 & 9"

- src/app/components/pages/Groups.tsx
- src/app/state/slices/api/groupsApi.ts
Invalidates the Groups tag in RTK as to pull the updated group data when removing a user. This prevents the need for filtering groups after making the request, which was previously buggy.
> Correctly update group when removing user

- src/app/components/content/IsaacQuestion.tsx
- src/app/components/navigation/RevisionWarningBanner.tsx
- src/app/components/pages/Question.tsx
- src/app/state/selectors.tsx
If a user is in revision mode (thus their previous attempts are hidden)
and are attempting a question where some of the question parts have
previous attempts a banner is shown at the top of the question
explaining why their attempts have been hidden.
There is a link to the beta feature page to turn the revision mode off
if the student wishes to see their previous answer.
> Display warning banner when attempts hidden due to revision mode

- src/app/components/pages/GameboardFilter.tsx
- src/app/services/userContext.ts
Provides a temporary solution for the URL parameters not updating as stage/topic/fields in the Question Finder page are removed from the search.
Seemingly, `history.replace` does not update a search query if the new parameters are a strict subset of the ones provided previously; this solution therefore resets them before replacing.
A much better solution exists with `react-router-dom` v6, which we should consider upgrading to alongside the planned React upgrade.
> Question finder URL not updating when field removed

- src/app/components/elements/inputs/CountryInput.tsx
- src/app/components/elements/inputs/DropdownInput.tsx
- src/app/components/elements/panels/UserProfile.tsx
- src/app/components/pages/RegistrationSetDetails.tsx
- src/app/services/validation.ts
While the field would display as `invalid`, this wasn't preventing form submission as it should. The form feedback for the field also wasn't displaying because `<FormFeedback />` needs to be adjacent to `<Input />`.
I didn't add this to the submission check on My Account, as it might be confusing for users to be unable to update fields on other tabs due to country now being truly required, but maybe there's an argument for doing that.
> Add country field validation to Ada signup flow

- src/app/components/content/IsaacQuestion.tsx
After submission the focus on the page resets to `body` which means
using a screenreader (or tabbing) takes the user to the top of the page.
As the submit button disappears after a correct submission the response
banner is focused instead. This way the user can continue from the
question answer. This does require making the `div` tabbable,
which should ideally mean that element is responsive (which it is not),
as otherwise it cannot be focused on.
> Prevent screenreader page jump on question submission

- src/app/components/elements/markup/markdownRendering.ts
Safari's spacing around `inline-block` elements is inconsistent with other browsers. This changes the outermost display type to `inline-flex` for inline regions which seems more consistent.
> Fix spacing issue with multiple inline zones

- src/app/components/elements/markup/markdownRendering.ts
- src/scss/common/questions.scss
- Clicking unit buttons would add a border and thus increase the size of the button by 2px, but the adjacent input would not change;
- Since fixing inline regions on Safari by changing the inline span to use `d-inline-flex`, elements with whitespace to either side are now left-aligned rather than the usual centre-aligned. This adds a `justify-content-center` to remedy this.
> Fix spacing issues for inline questions

- src/app/services/gameboardBuilder.ts
There have been errors in the back-end logs from created gameboards not getting deserialized because of the inclusion of fields that do not exist in the GameboardItemDTO.
In the front-end conversion from ContentSummary objects to GameboardItems a "deprecated" field was not being removed.
This PR uses the type system to ensure that we remove all ContentSummary fields that are not expected in GameboardItems and will check at compile time if fields are removed or added to either type in the future.
> Assert correct ContentSummary to GameboardItem conversion

- src/IsaacApiTypes.tsx
- src/IsaacAppTypes.tsx
- src/app/components/elements/inputs/StyledCheckbox.tsx
- src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
- src/app/components/pages/QuestionFinder.tsx
- src/app/services/api.ts
- src/app/services/constants.ts
- src/app/state/reducers/gameboardsState.ts
- src/scss/common/checkbox.scss
- Highlights results in the question finder green if previously answered correctly (using the same marking as related questions);
- Adds a toggle to hide previously answered questions;
- Adds a "Load More" button, which pulls `min(30, relevant_questions_remaining)` questions from the backend.
> Add pagination and attempt data to question finder

- src/app/components/pages/QuestionFinder.tsx
This also means removing the search text removes the search query rather
than unintuitively having to press enter.
> Improve Question Finder search box

- src/app/components/elements/inputs/UserContextPicker.tsx
- src/app/components/navigation/IntendedAudienceWarningBanner.tsx
When changing the stage in the context picker, if the possible exam boards had just one option besides All, it would visually display this option but not modify the URL. As such, the "no content" warning could describe a different exam board to that which was visually shown.
This also updates the text of the warning banner per request.
> "All exam boards" context picker improvements

- src/app/components/pages/QuestionFinder.tsx
Prevents users clicking the "Load more" button multiple times, which was creating several duplicate API requests.
> Disable load more when clicked once

- src/app/components/elements/cards/NewsCard.tsx
- src/app/components/pages/OnlineCourses.tsx
- src/app/components/site/cs/HeaderCS.tsx
- src/app/components/site/cs/RoutesCS.tsx
Adds a news-style page for external RPF online courses. Uses the same pods endpoint as news, but with the `online_courses` tag.
> Add Ada Online Courses page

- src/app/components/elements/cards/NewsCard.tsx
- src/app/components/pages/OnlineCourses.tsx
- src/scss/common/_mixins.scss
- src/scss/common/cards.scss
- src/scss/common/elements.scss
- src/scss/phy/cards.scss
Forces images into the same aspect ratio.
Isaac:
- News Pods: 5:3
Ada:
- News Pods: 4:3
- Online Courses Pods: 5:3
> Make image aspect ratios consistent per page

- src/app/components/content/IsaacInlineRegion.tsx
- src/app/components/elements/markup/portals/InlineEntryZone.tsx
On following a soft-link to an inline question, the new page's IsaacInlineRegion is rendered before the questions have been registered and elementToQuestionMap has been built. We have updated the type to allow for this and, importantly, added the value to the dependencies of the useEffect that registers the question parts so that the inline regions render when the data is available.
> Allow for inline q details to be undefined on 1st render after soft-link-follow

- src/app/components/elements/inputs/InlineNumericEntryZone.tsx
- src/app/components/elements/inputs/InlineStringEntryZone.tsx
- src/app/components/elements/markup/markdownRendering.ts
- src/scss/common/questions.scss
Fixes the issue with boxes appearing too high until they are typed in on Safari. No noticeable differences on any other browser.
> Fix inline box positioning on Safari

- src/app/components/elements/markup/portals/InlineEntryZone.tsx
Prevent the inline feedback index showing as 0 when loading a page with inline questions from the "next question" button on a gameboard.
> Inline feedback index on soft links

- deploy.py
The deploy script currently expects previously running containers to exist. It both queries these containers and brings them down.
The standby server has no containers running and therefore the script fails when attempted on the standby server. This PR skips commands that use the old containers when it detects they are not running and adjust commands as necessary.
Support for staging, test, and dev have not been added as these are unlikely to be required on the standby server.
> Allow deploy script on the standby server

- src/IsaacAppTypes.tsx
- src/app/components/content/IsaacClozeQuestion.tsx
- src/app/components/elements/markup/portals/InlineDropZones.tsx
- src/app/components/elements/modals/ExtendDueDateModal.tsx
- src/app/services/constants.ts
- src/scss/common/icons.scss
- src/scss/common/print.scss
- src/scss/common/questions.scss
- src/scss/cs/questions.scss
When the screen is small (e.g. a mobile device) the drop zones are converted to dropdown menus with the available items. The item tray is removed.
If there is no replacement then selecting an item removes it from other dropdowns. A blank option is added to allow for resetting individual zones.
This requires a new handler function in the IsaacClozeQuestion component that is passed to the InlineDropZone rendering component through the DropRegionContext. This is an altered version of the onDragEnd handler.
> Use dropdown menus for cloze questions on mobile

- src/app/components/pages/RegistrationSetDetails.tsx
In the old signup flow, the required account info modal would pop up incessantly if this was left undefined (although could still be skipped). In the new flow, the preferences stage of the flow is a lot easier to skip once and forget about, so it's best to set this upon initial account creation and update it later.
> Set email preference defaults on account creation for Ada

- src/app/components/site/cs/HeaderCS.tsx
On Ada CS, show teachers an indicator by 'Work to do' if they have assignments to complete.
> Add indicator by 'Work to do'

- src/app/components/pages/ExamSpecificationsDirectory.tsx
- src/app/components/site/cs/HomepageCS.tsx
- src/app/components/site/cs/RoutesCS.tsx
Replaces the temporary concept page for SQA exam specifications with a new `ExamSpecifications`-based page.
> Add new ExamSpecification page for SQA

- src/app/components/site/phy/FooterPhy.tsx
Footer changed from:
```
"Funded by Department for Education.
Supported by The Ogden Trust."
```
to:
```
"Funded by University of Cambridge.
Supported by Department for Education and The Ogden Trust."
```
> Update footer to add University funding

- src/IsaacAppTypes.tsx
- src/app/components/content/IsaacClozeQuestion.tsx
- src/app/components/elements/markup/portals/InlineDropZones.tsx
- src/scss/common/questions.scss
Limits the size of cloze dropdown menus and adds scrollbar on vertical overflow.
Greys out previously selected options on non-replaceable cloze questions rather than removing them from the dropdown.
[Example for scrolling](https://isaacphysics.org/questions/hypothesis_meeples?stage=all)
[Example for non-replaceable questions](https://isaacphysics.org/questions/itsp_density_hw_q2?stage=all)
> Cloze dropdown scrolling and greying out

- src/scss/common/print.scss
- src/scss/common/questions.scss
Adds both a `border-color: black;` to cloze items when printing, and a default `border-color: $border-color` for cloze questions in general so it still appears when the default forced-colors scheme is enabled (overridden normally).
> Restore black border to cloze items when printing

- src/app/components/content/IsaacQuestion.tsx
Prevent the submission of a numerical answer that has no value, regardless of whether it has units.
The null and "" cases are both needed depending on whether the question has been previously attempted.
> Prevent blank answer submission

- src/app/components/elements/GameboardBuilderRow.tsx
On Ada CS, prevent the quiz builder listing an exam board more than once for the same question.
> Fix duplicate exam boards

- src/app/components/elements/ReportAccordionButton.tsx
- src/app/services/userViewingContext.ts
When the report flag is clicked on a specific question part, ensure the section title passed to the report page's
URL does not contain ampersands.
> Remove ampersands from report URLs

- src/app/components/content/IsaacSymbolicQuestion.tsx
- src/test/components/content/IsaacNumericQuestion.test.tsx
- src/test/components/content/IsaacSymbolicQuestion.test.tsx
If a symbolic input contains more than one equals/inequality sign, show instant feedback that this is not allowed.
> Show warning for double inequalities

- src/app/services/userViewingContext.ts
On Ada CS, if a question is tagged as both core and advanced, display both stage labels.
> Display core and advanced stages

- src/app/components/elements/markup/portals/InlineDropZones.tsx
On cloze dropdowns (mobile), replace the blank dropdown option with 'Clear' text.
> Change clear dropdown option

- src/app/components/elements/inputs/TrueFalseRadioInput.tsx
- src/app/components/elements/inputs/UserContextAccountInput.tsx
- src/app/components/pages/RegistrationSetPreferences.tsx
- src/app/services/validation.ts
Applies changes to the final page on signup:
- Makes all fields mandatory on physics
- Disable "set preferences" button if not complete ("skip" is always accessible)
> Phy signup preferences form improvements

- src/app/components/navigation/NavigationBar.tsx
'MENU' button was moved too close to search icon on small/medium screens. This restores spacing to the original layout.
> Restore NavBar mobile alignment

- src/app/components/pages/QuestionFinder.tsx
In the new question finder, implement a 255 character limit in the search box.
> Add char limit to QF search

- src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
In cases where the user information is not loaded (e.g. global site search), the CSLGI's `item.state` is undefined, which was leading to no icon being displayed. This sets the default case for a switch on `item.state` to use the `NOT_ATTEMPTED` icon instead.
> Use default question icon when user info not loaded

- src/app/components/pages/QuestionFinder.tsx
Adds a new logged event for Question Finder search, for example:
`QUESTION_FINDER_SEARCH`| ... | `"{""events"": {""book"": [], ""stages"": [""gcse""], ""topics"": [], ""examBoards"": [""ocr""], ""startIndex"": 0, ""difficulties"": [], ""searchString"": ""e"", ""questionStatuses"": {""complete"": false, ""tryAgain"": false, ""notAttempted"": false}}}"`
> Add logged event for Question Finder search

- src/app/components/elements/panels/TeacherConnections.tsx
- src/app/components/pages/OnlineCourses.tsx
- src/app/components/pages/quizzes/SetQuizzes.tsx
- src/scss/common/header.scss
- src/scss/common/my-account.scss
- src/scss/phy/questions.scss
Fixes a number of spacing and text overlap issues found during regression testing:
- Teacher connections panel rows must be fixed height (by virtue of React Window) so each line of text is now limited to that one line and will cut off with an ellipsis if longer;
- For the groups panel only, the full, non-cut-off group title will show on hover (and is accessible through screenreader, as are all cut-off strings);
- Fixes Ada Online Courses overlap on Firefox;
- Aligns the Phy board hexagon on Set Tests;
- Extends the max-height of toasts.
> Various spacing issues

- src/scss/common/questions.scss
Prevents dropdown clipping for both sm-width cloze questions and inline unit selectors when around latex.
The automatic scrollbar padding has been removed as this approach was not working and cannot work; it relied on the existence of the scrollbar to set `$cloze-scrollbar-height`, but when opening the menu the scrollbar must be hidden (else the menu clips behind it), but this means there is no scrollbar to set `$cloze-scrollbar-height` any longer.
> Fix dropdowns being clipped around latex

- src/app/components/navigation/IsaacApp.tsx
Will require _"refNo"_ to be added to the Field Editor on Qualtrics surveys in order to be tracked (as with UID).
Should be fully backwards compatible with old links. 
**Old:** https://isaacphysics.org/survey/{surveyId}
**New:**  https://isaacphysics.org/survey/{surveyId}/{refNo}
The line `${refNo ? '&refNo=${refNo}' : ''}` is used to remove _"&refNo=undefined"_ from links that do not include a reference, but this isn't strictly necessary.
> Add optional refNo to Qualtrics links

- src/app/components/elements/GameboardBuilderRow.tsx
- src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
- src/scss/phy/isaac.scss
- src/scss/phy/search.scss
Adds "superseded" and "nofilter" info bubbles to questions when displaying on the question finder, site search and gameboard builder. 
"Superseded" questions can be seen by teachers in both the QF and site search, and will appear in the gameboard builder on questions they have previously set that have since been superseded. The "nofilter" tag can by design only be seen by staff, as these questions are not otherwise displayed.
> Superseded / nofilter info bubbles

- src/app/state/actions/index.tsx
Adds an `EmailChangeModal` to tell users upon changing email to verify their new address by following the verification link (previously a browser alert)
The logic of the rest of the `updateCurrentUser(...)` function is moved into two separate functions called depending on modal output (or `continueSettingsUpdate()` is always called if no modal is necessary).
> Switch email edit notice from alert to modal

- src/app/components/elements/markup/portals/InlineDropZones.tsx
Use dropdowns instead of drop zones for cloze questions on any touchscreen device. Keep the size breakpoint for small screens of any type.
Using maxTouchPoints for this seems to work, but there's probably a neater way to actually detect the device type.
> Use cloze dropdowns on touchscreens

- src/app/components/elements/inputs/InlineNumericEntryZone.tsx
Prevents duplication of `data-unit=None` in unit selection for both the empty selection and the genuine "no unit" selection.
> Differentiate `data-unit` across undefined / empty unit

- src/app/components/elements/panels/QuestionFinderFilterPanel.tsx
- src/app/components/pages/QuestionFinder.tsx
- src/app/services/userViewingContext.ts
On Ada, if a user has more than one context set on their account preferences, don't set any question finder filters by default.
Users with a single context set should have the filters set as before.
> Deselect QF filters for multiple contexts

- src/app/components/content/IsaacCoordinateQuestion.tsx
For coordinate questions, give instant feedback if a fraction (or other invalid numerical expression) is input.
> Add fractional coordinate warning

- src/app/components/elements/inputs/InlineNumericEntryZone.tsx
- src/app/components/elements/markup/portals/InlineDropZones.tsx
Ensures dropdowns are not cut off by ancestor elements with `overflow`s set (e.g. tables). This works by moving the container of the dropdown from being a child of the source `<DropdownToggle/>` button to being a child of the closest `question-content` ancestor for inline and cloze dropdowns. This ensures that relevant CSS styling can still be applied -- for example, to ensure the max-height of a `cloze-question.dropdown` is adhered to.
> Dropdown usability improvements

- src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
- src/app/services/questions.ts
Chemistry text entry symbols are not consistent with their symbol names in the rest of the app, to aid in lexing.
e.g. `alpha` -> `\alphaparticle`
(We can consider revising these text entry symbols later)
Translating this in `question.ts` caused some issues with recognizing the symbols in the wrong places, so I've reduced it just to the scope of the text where it's needed in `IsaacSymbolicChemistryQuestion.tsx` (for _"The following symbols may be useful: ..."_). 
This should make it have no effect on the rest of the app.
> Fix Chemistry symbols not showing up in Inequality menu

- src/app/components/elements/modals/QuizSettingModal.tsx
A change [here](https://github.com/isaacphysics/isaac-react-app/pull/1071) added a front-end warning and disabling of invalid groups (for which the quiz had already been set) in the dropdown menu.
This reverts the disabling in the dropdown menu (since it was unclear what was happening) but keeps the front-end warning.
(I also noticed that the check for passing due date was checking for the past instead of the future so that's been fixed here too)
> Revert invalid group greying in Set Quiz modal

- src/app/components/content/IsaacClozeQuestion.tsx
- src/app/services/device.ts
Some versions of Firefox set maxTouchPoints to 256, incorrectly flagging the device as touchscreen.
> Fix touchscreen dropdowns

- src/app/components/elements/GameboardBuilderRow.tsx
- src/app/components/pages/GameboardBuilder.tsx
- src/scss/common/table.scss
- src/scss/cs/table.scss
- src/scss/phy/table.scss
With the new changes to `GameboardBuilderRow`s, there are multiple rows inside a `<Draggable/>`. This is illegal usage (hence the problematic appearance), and so must be wrapped inside a parent element. Unfortunately, being a group of `<tr/>`s, the only valid parent element is a `<tbody/>`. Having multiple `tbody`s is valid in the HTML spec so this is okay; we then move the `<Droppable/>` context around the `<table/>` as that must be above the `<Draggable/>`s (and table is the only valid tag around tbody). 
This, however, worsens an issue with the existing GBR; while dragging, the `<tbody/>` loses its tablular display, and with the new changes this is particularly noticeable.  We can reset this display via `display: table`, but must only apply this while dragging, else this breaks the …
> Fix dragging rows on the gameboard builder

- src/IsaacAppTypes.tsx
- src/app/components/content/IsaacInlineRegion.tsx
- src/app/components/content/IsaacQuestion.tsx
- src/app/components/elements/InlineContextProvider.tsx
Adds an `initialised` flag to the inline context to account for portals rendering order differing on soft links.
Soft and hard link redirects having different rendering behaviour is the real cause and this only patches over this, so we should perhaps consider an alternative portals approach in the future.
> Ensure inline entries are rendered on soft link follow

- src/app/components/elements/panels/TeacherConnections.tsx
- src/app/components/pages/MyAccount.tsx
- src/app/components/pages/RegistrationGroupInvite.tsx
- src/app/components/site/phy/RoutesPhy.tsx
When users sign up following a group join link, add a page after the signup flow to confirm that they want to share their data with teachers. This replaces a modal with similar behaviour.
This could just be an extra question at the bottom of the signup page, but the new buttons would look confusing next to the existing Back/Continue buttons.
The exact wording used and failure modes might also need to be reconsidered - currently users can complete the entire signup flow before finding out their link was invalid.
> Add group join page to signup flow

- src/app/services/userViewingContext.ts
- src/scss/cs/accordions.scss
If a single audience stage exists that stage's colour is used. If multiple stages exist then the stages are grouped into "core" and "advanced". If all of the stages are a single group then that group's colouring is used, otherwise the standard colour mix (yellow) is used.
> Improve Ada accordion colour styling

- src/app/components/pages/quizzes/SetQuizzes.tsx
Hide tests with the 'deprecated' flag from all users on the 'set tests' page. Previously set tests which are now deprecated should still show up under 'manage tests' (and can be re-set from here, which should perhaps be disabled).
This also requires a change in the editor to show the 'deprecated' flag for tests.
> Hide deprecated tests

- src/app/components/pages/RegistrationSetDetails.tsx
The code, for the previous couple of months, has tried to set the default viewing context during registration but the back-end code ignores it. We actually do not want to be setting the default viewing context at this step in the registration because we want to continue to display the context picker to users who have not explicitly set them.
> Stop setting viewing context defaults on registration as not saved in DB

- src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
- src/app/components/content/IsaacSymbolicLogicQuestion.tsx
- src/app/components/content/IsaacSymbolicQuestion.tsx
Since the update to React 18, a new exception was firing whereby removing the element over which tooltip hover text was active would give an obscure error from inside the ReactStrap library.
> Fix Inequality 'reading 0' exception

- src/app/components/elements/cards/BoardCard.tsx
Fixes a small bug where invalid hexagon IDs could be passed to HexagonGroupsButton. This wasn't affecting the live site, but could cause an error on staging.
> Sanitise hexagon board IDs

- src/app/components/pages/Gameboard.tsx
For students on physics: if a gameboard question has a difficulty that matches the student's stage, show them only the difficulty for that stage.
> Show fewer difficulties on gameboards

- src/app/components/content/IsaacCodeTabs.tsx
- src/app/components/content/IsaacContentValueOrChildren.tsx
- src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
In an effort to finally implement `codeTabs` into the app (to allow a user's preferred programming language to be automatically selected), it was found that they don't work for tabs with anything other than a single `codeSnippet` child. 
This genericises the child to all children in a `Content` block, which is then handled by `Tabs` as normal.
> Allow codeTabs to have non codeSnippet children

- src/app/components/content/IsaacCoordinateQuestion.tsx
- src/app/components/content/IsaacNumericQuestion.tsx
For coordinate questions: change the way coordinates are concatenated before being validated to avoid negative numbers erroneously being flagged as invalid.
Also implement invalid character checks in the same style as numeric questions.
> Fix coordinate feedback

- src/app/components/pages/TeachingOrders.tsx
- src/app/components/site/cs/RoutesCS.tsx
On Ada, create a new suggested teaching order page. This is in addition to the current page until the relevant fragments are created.
> Create new teaching order page

- src/app/services/numericUnits.ts
If a question has at least one manually chosen incorrect unit option, don't add any random units to the dropdown.
> Stop adding random unit options

- package.json
- src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
- src/app/components/elements/modals/inequality/InequalityModal.tsx
- src/app/components/elements/modals/inequality/constants.ts
- src/app/components/elements/modals/inequality/utils.ts
- src/app/components/pages/Equality.tsx
- yarn.lock
Prefixes represent mass and proton numbers. These are only used during Nuclear Physics questions, so can be disabled for ease-of-use in Chemistry questions.
For react-app, this basically consists of adding `"nuclear"` as an `EditorMode`, which is already passed to Inequality for it to handle. This also allows for other front-end enhancements e.g. also disabling the "state symbols" tab for Nuclear questions.
Inequality change [here](https://github.com/isaacphysics/inequality/pull/8).
> Remove prefix (Nuclear) docking points for Chemistry questions in Inequality

- src/app/components/elements/panels/TeacherConnections.tsx
If an Ada user tries to join a group via the account page's connections tab any time during their first session after registration they get redirected to a page which only exists for Physics. It is possible that there are other routes to this broken redirect.
I'm unsure if the redirect is wanted in this particular case for Physics users either. My understanding was that the new page would only be used during the registration process but this requirement might have been asked for during discussion with the content team.
> Remove redirect to non-existent ada route

- src/app/components/pages/MyAccount.tsx
- src/app/services/constants.ts
Adds `#security`, `#connections` and `#notifications`, to be shorter and/or in-line with the tab headings.
**Does not remove the old anchors.** All prior links still work.
> Alias account tab hash anchors

- package.json
- yarn.lock
Updating inequality-grammar to (edit) 1.3.4 to allow individual elements to be bracketed (or hydrated), and allow zero-values on input.
(@jsharkey13)
> Update Inequality Grammar to v1.3.4

- src/app/components/pages/quizzes/MyQuizzes.tsx
Show the 'visible to students'/'hidden from teachers' labels from Set Tests on My Tests > Practice Tests.
> Show test visibility in My Tests

- src/app/components/content/IsaacSymbolicQuestion.tsx
InequalityModal is a lazily-loaded component, loaded when the user opens the inequality box. Being lazy, while the component data is being fetched after being required, it *suspends*. A suspended component will not render anything until all the data has been fetched, at which point the entire parent is rerendered -- *unless* it exists around a `<Suspense/>` boundary, in which case the component defined in the `fallback` prop  is rendered in the meantime, and *only the contents of the Suspense boundary are rendered*.
Previously, `<InequalityModal/>` did not have a `<Suspense/>` without a wrapper boundary. Therefore, the **entire** parent div was rerendering once the data loaded. Included in the parent component is 1. the entire contents of the question, and 2. the help component. The …
> Fully fix "reading 0" exception around Inequality

- src/app/components/pages/ExamSpecifications.tsx
On Ada: if an exam specification page has stage/exam board tab options that match a user's context, default to those tabs when the page is loaded.
This works best for users with a single context set; if a user (teacher or above) has multiple contexts set, the tabs will default to the last match found.
> Default exam spec tabs to user context

- src/app/components/pages/QuestionFinder.tsx
We auto-populate the filter settings from account settings.
All stages and All exam boards are account options for now.
When their values are used to auto-populate the filters the search looks for content tagged `all` which we don't tag by.
Line 126 of the QuestionFinder file [here](https://github.com/isaacphysics/isaac-react-app/pull/1131/files) shows that we used to only update if it wasn't a "null option".
> Stop auto-filtering q finder with all option

- src/app/components/pages/Gameboard.tsx
- src/scss/cs/boards.scss
Decreases the footprint of the question status and the difficulty icons on Ada.
> Prevent overflow on mobile `/gameboard` view

- src/app/components/elements/inputs/UserContextPicker.tsx
For non-staff users: hide context picker.
For staff users: show all stage/exam boards options on context picker.
> Hide context picker for non-staff users

- src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
- src/app/components/elements/modals/inequality/InequalityModal.tsx
- src/app/components/pages/Equality.tsx
Forming a multiple-digit `numberInputValue` in the Inequality Modal was unlimited, which led to bad behaviour (e.g. overflowing from its menu container, large numbers facing integer limit issues, larger numbers being converted to scientific notation).
I've run a script to check all symbolic questions on the site and found 10 total questions with answers containing 4 or more digits:
- 7 of them would be fine with 4 positive digits
- The other 3 are just a single number and so can be answered very easily with just the existing text input (and don't even really need to be symbolic questions anyway!) [e.g. [Part A](https://isaacphysics.org/questions/iodate?stage=a_level)]
4 characters is also the amount that fit cleanly in the menu hexagon, so 4 positive digits / 3 negative digits is the …
> Limit multiple-digit numbers in Inequality

- src/app/components/pages/quizzes/MyQuizzes.tsx
`toSorted` is undefined on [older browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted#browser_compatibility), causing client errors in some cases. While some of these are out the scope of browsers we support, this is a painless fix with no real reason not to do.
> Prevent client error on old browsers on `/tests`

- src/app/components/elements/markup/portals/InlineEntryZone.tsx
Causes the inline correctness check to only occur when feedback is obtained, rather than additionally on page load.
> Prevent page load firing "on submission" `isUnanswered` check

- src/app/components/pages/AdminUserManager.tsx
Add a regex to verify that a postcode is of a sensible format in admin user search before sending it to the API. The regex should match complete postcodes (e.g. CB3 0FD) and outcodes (e.g. CB3).
This check doesn't verify that a postcode actually exists, so a server error can still be thrown in some cases, but this should reduce the chances of this happening.
> Add admin search postcode validation

- src/app/components/elements/inputs/InlineMultiChoiceEntryZone.tsx
- src/app/components/elements/markup/portals/InlineDropZones.tsx
- src/app/components/elements/markup/portals/InlineEntryZone.tsx
- src/app/services/constants.ts
- src/scss/common/icons.scss
- src/scss/common/questions.scss
- src/scss/cs/questions.scss
- src/scss/phy/questions.scss
Adds a new type of inline question, multiple choice, that creates a dropdown similar to (but slightly distinct from in structure) cloze questions in mobile view.
Also adds some type checking to `InlineEntryZone` such that adding further new inline questions is even easier, and collates all border / shadow colouring into the same place.
> Add inline multiple choice questions

- package.json
- src/IsaacAppTypes.tsx
- src/app/components/elements/CardGrid.tsx
- src/app/components/elements/CollapsibleContainer.tsx
- src/app/components/elements/CollapsibleList.tsx
- src/app/components/elements/Gameboards.tsx
- src/app/components/elements/SortableItemHeader.tsx
- src/app/components/elements/modals/QuestionSearchModal.tsx
- src/app/components/elements/quiz/QuizProgressCommon.tsx
- src/app/components/elements/svg/FilterCount.tsx
- src/app/components/elements/tables/TableLinks.tsx
- src/app/components/pages/AssignmentSchedule.tsx
- src/app/components/pages/MyGameboards.tsx
- src/app/components/pages/SetAssignments.tsx
- src/app/components/pages/quizzes/MyQuizzes.tsx
- src/app/components/pages/quizzes/PracticeQuizzes.tsx
- src/app/components/site/cs/RoutesCS.tsx
- src/app/components/site/phy/NavigationBarPhy.tsx
- src/app/components/site/phy/RoutesPhy.tsx
- src/app/services/gameboards.tsx
- src/app/services/quiz.ts
- src/app/state/slices/api/gameboardApi.ts
- src/scss/common/elements.scss
- src/scss/common/gameboard.scss
- src/scss/common/icons.scss
- src/scss/common/quiz.scss
- src/scss/common/table.scss
- Splits the listing of available practice tests into its own page, `/practice_tests`, accessible via the Learn nav;
- Creates a new default table view for `/tests` (though the original card view is still accessible), which displays the title, assigner and relevant dates;
- Splits assigned tests from practice tests into separate tabs at the topmost level of `/tests`; further filtering inside these categories (for started, not yet started, overdue and completed) can be achieved via the filters menu
> Distinguish Practice Tests

- src/app/components/pages/quizzes/PracticeQuizzes.tsx
This is a temporary stopgap solution so teachers cannot see practice tests that can't be attempted (and which lead to an error page) on the new dedicated "Practice Tests" page.
These tests can still be previewed on the "Set Tests" page as normal, and we'll likely allow them to be attempted in another change soon - at which point this can be reverted.
> Remove non-attemptable practice tests for teachers

- src/app/services/userViewingContext.ts
At the start of the year we added logic to `isIntendedAudience` that returns `false` early if the content's audience field does not include an exam board. I believe we did this to keep non spec-aligned content (such as the AI topics) from appearing as "on your specification" - at the time we didn't have Core and Advanced so these had no audience tags, and content without any audiences defined defaulted to on-spec.
This causes a problem for Teacher Resources accordion sections, which define their audience based on role only and have no exam board field, so by this logic are always hidden.
Now all content should be tagged Ada and either Core or Advanced, so this should be safe to remove.
> Fix intended audience logic for content where only a role is specified

- package.json
- src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
- src/app/components/content/IsaacSymbolicLogicQuestion.tsx
- src/app/components/content/IsaacSymbolicQuestion.tsx
- src/app/components/elements/modals/inequality/InequalityModal.tsx
- src/app/components/elements/modals/inequality/utils.ts
- src/app/components/pages/Equality.tsx
- yarn.lock
If `makeInequality` is called with an undefined ref, p5 proceeds to generate a new canvas at root level with seemingly fullscreen sizing. With an adjacent change to [inequality](https://github.com/isaacphysics/inequality/pull/10), this forces the element to always be defined and will quietly cancel the setup in the known cases when this occurs.
> Inequality producing empty canvases at root level on resize

- src/app/components/pages/Equality.tsx
The bug is that text entry sometimes doesn't work on switching modes on the demo page. To recreate:
1. Go to [staging.isaacphysics.org/equality](http://staging.isaacphysics.org/equality) (logged into an admin account)
2. Choose ‘Nuclear Physics’ from the dropdown
3. Type “H”
4. Click to enter Inequality modal
5. Submit
6. Try to edit the text input prescripts (e.g. "{}^{2}_{}H")
This is broken (only for the demo page) due to the `editorMode` for inequality text entry (`hiddenEditorRef`) only being set when the main inequality `editorMode` changes, but the page reload forcing text entry to be generated again. This regenerated `hiddenEditorRef` therefore doesn’t have `editorMode` set, so it is set to the default of “logic”.
The solution is simply to pass the main `editorMode` into …
> Pass editorMode into text entry's Inequality reference on the equality demo page

- package.json
- yarn.lock
This change to Inequality disables various docking points (the circular points that each widget attaches to) depending on Inequality's `editorMode` being `'chemistry'`/`'nuclear'`. This includes:
- Anything docking to the Exponent of Numbers
- BinaryOperation (plus/minus) docking to Relations (reaction arrows) or to the right of Operators (numbers)
- Brackets docking to Exponent/Subscript slots or to the right of Operators (numbers)
- Numbers docking to the right of Brackets
- (Nuclear only) Anything docking the Exponent/Subscripts of Elements
- (Nuclear only) Anything docking to Subscripts of Particles (Exponents are needed for e.g. positrons)
> Update Inequality to 1.2.0

- src/app/components/navigation/IsaacApp.tsx
- src/app/components/pages/AssignmentSchedule.tsx
- src/app/components/pages/Gameboard.tsx
- src/app/components/pages/MyGameboards.tsx
- src/test/pages/AssignmentSchedule.cy.tsx
Replace or remove references to gameboard filter, and restricts the gameboard filter to logged in users.
This is softer than the blanket removal we promised for Jan 2025.
Since the filter is gone, there is no need to allow the "filter=true" URL parameter to work any more.
We may want to re-use the code from extractFilterQueryString if we ever decide to add links from gameboards to the new question finder, but I have removed it for now since it was unused and doing so allows removing the library too.
> Deprecate Gameboard Filter

- src/app/components/elements/cards/EventCard.tsx
- src/app/components/elements/cards/NewsCard.tsx
- src/app/components/pages/Events.tsx
- src/app/components/pages/News.tsx
- src/scss/phy/cards.scss
Suggests some changes to the pods components.
- Make image sizes consistent between pods; increase size for vertically-stacked pod;
- Fix odd placement of `event-pod-badge`;
- Ensure the `@container` query lines up with `md` breakpoint when including padding;
- Aligns the structure of News pods and Event pods to be as similar as possible.
(On a related note, I'm tempted to make them the same component, or at least both inherit a common abstract structure so that changes to one would reflect in the other; the current way of doing it where we have two entirely separate components that generate almost the same thing is definitely redundant. Let's leave this for another time though, as it'll affect Ada too.)
> Pod suggestions

- src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
- src/app/components/content/IsaacSymbolicLogicQuestion.tsx
- src/app/components/content/IsaacSymbolicQuestion.tsx
Currently, `editorMode` is not always instantiated for inequality’s text input. Often this doesn't matter, but when each mode has a different valid input (e.g. the exponent docking point being removed for Chemistry but kept in Maths) and `editorMode` has not been instantiated, it defaults to the less expressive input.
Text entry normally copies parameters from symbolic entry, but this causes a race condition. `editorMode` can simply be hard-coded into each editor’s text entry box to avoid this.
> Set Inequality text editor mode strictly

- src/IsaacApiTypes.tsx
- src/app/components/content/IsaacCoordinateQuestion.tsx
Moving to using an array means we don't load the x and y values from existing answers. This supports doing that, whilst cleaning the updated choice so that if it is submitted again there is no sign of the old-style properties.
> Allow loading of old-style coordinate answers

- src/app/components/elements/modals/inequality/InequalityModal.tsx
Currently, Inequality menus with sub-menus (_Maths->Letters_, _Boolean->Letters_, _Maths->Other Functions_) don't have their main button collapse the menu, but those without sub-menus do.
This is essentially because the same logic is used for sub-menu buttons (at the very top of the screen) and the dropped down main menu buttons. `isSubMenu` can be used to differentiate between these, so adding a check for this to the `openNewMenuTab` call here fixes the problem.
> Allow menu collapse on options with submenus

- src/app/components/content/IsaacNumericQuestion.tsx
- src/app/components/elements/markup/index.tsx
- src/app/components/elements/markup/latexRendering.ts
Button elements are only allowed to contain presentational content for the accessibility tree; but <math> elements are semantic and will not be used by the screenreader. So the MathML is unhelpful here and every button was read out the same way, leaving questions unanswerable.
> Use alt text and not MathML inside button elements

- src/app/components/elements/PrintButton.tsx
- src/app/components/elements/ShareLink.tsx
- src/app/components/elements/inputs/UserContextPicker.tsx
- src/app/components/elements/layout/SidebarLayout.tsx
- src/app/components/elements/markup/markdownRendering.ts
- src/app/components/pages/Concept.tsx
- src/app/components/pages/Concepts.tsx
- src/scss/common/scroll-button.scss
- src/scss/cs/button.scss
- src/scss/cs/questions.scss
- src/scss/phy/button.scss
- src/scss/phy/questions.scss
- src/scss/phy/typography.scss
Applies design changes to concept pages.
Note that some changes to concept pages have already been merged owing to the [context overhaul](https://github.com/isaacphysics/isaac-react-app/pull/1341) PR being based off the first half of this commit. The changes here are an extension of these, cleaning up odd bits on the page.
Note that the `a-link` lightbulb icons do not all work in dev, as links to content pages are not seen as local if they start `https://isaacphysics.org/`, as some do. `cp_ang_eq_of_motion` has correct links if you need a page to test.
> Redesign concept pages

- src/app/components/content/IsaacCoordinateQuestion.tsx
The "default" item had an empty coordinates array in it; if it was not modified by the user, it was treated as a zero dimensional coordinate by the validator and misleading feedback was provided. The number of dimensions can't be known outside the question, so some refactoring was required. The spread syntax to clone the (mutable!) default item was quite subtle, so I moved it to a function returning a new item every time.
Also consistently default to 2 not 1 dimensions if the value is undefined (this should not be possible, but is now consistent with the code in the API).
> Ensure coordinate questions use correct dimensions

- src/app/components/elements/svg/PhyHexIcon.tsx
There was some padding from `PhyHexIcon` being applied to Ada titles. Since we never want hex icons on Ada, it seems sensible to just wrap the whole component in an `isPhy`.
> Fix Ada title indentation

- src/app/components/elements/layout/SidebarLayout.tsx
- src/app/components/pages/Generic.tsx
- src/app/components/pages/subjectLandingPageComponents.ts
- Add sidebars to general pages
- For the accessibility/policy pages this is fully implemented
- For all other general pages this is just a link to the homepage, pending a decision on what should go here
- Add "no related content" messages to question sidebars
> Redesign - start implementing general page sidebars

- src/app/services/gameboards.tsx
Context: After creating a new gameboard and clicking "set as assignment", the assignment setting modal was not opening.
Explanation: When "set as assignment" is clicked, the ID of the new gameboard is stored in a hash anchor. The modal then works by taking the first 6 gameboards from the `useGameboards` hook and checking their IDs against the hash anchor to determine which gameboard to use. This previously worked because `useGameboards` returned gameboards sorted most-recent-first, so the just-created gameboard is always among the 6 returned. A previous change on the redesign branch reversed the order in which gameboards are returned, so the ID in the hash anchor was not found if the user had > 6 gameboards and no modal appeared.
The solution proposed here is just to revert the sorting …
> Fix assignment modal bug

- src/app/components/elements/markup/portals/InlineEntryZone.tsx
- src/app/services/constants.ts
Enables regex as a question type to be marked inline. Uses the same entry field as string match; some typing is technically incorrect because of this (i.e. TS assumes the question is a StringMatchQ as opposed to a RegexMatchQ), but only base class props are used so this is not an issue. Might genericise in future if necessary.
> Add support for inline regex questions

- src/app/components/elements/panels/AddUsersToBooking.tsx
- src/app/components/pages/Admin.tsx
- src/app/components/pages/AdminEmails.tsx
- src/app/components/pages/AdminUserManager.tsx
- src/app/components/pages/Equality.tsx
- src/app/components/pages/FreeTextBuilder.tsx
- Remove borders around "Useful links" (both sites)
- Add borders to buttons (phy)
- Improve padding & alignment of buttons (both sites)
> Improve admin pages styling

- src/app/components/elements/Assignments.tsx
- src/app/components/elements/StudentDashboard.tsx
- src/app/components/elements/TeacherDashboard.tsx
- src/app/services/assignments.ts
The homepage dashboards weren't showing assignments/quizzes due today because they were considered overdue. This was inconsistent with My Assignments, which doesn't consider an assignment overdue until midnight at the _end_ of the due date. Both places now use the same `isOverdue` function which maintains the current My Assignments behaviour.
(This also fixes some edge cases for the student dashboard where having assignments due today prevented the next-soonest assignments from being shown).
> Redesign: change dashboard due date logic

- src/app/components/elements/modals/QuestionSearchModal.tsx
- src/app/components/pages/QuestionFinder.tsx
All blank or empty parameters can be undefined for the search, which means they won't be included in the API call URL in silly ways like e.g. /questions?searchString=&tags=&examBoards=&subjects=physics&... in every single request.
The API treats these empty string values identically to the null case, except "statuses", where the empty string means "don't filter by status but _do_ augment results with attempt data". So for the question finder, this argument must never be undefined but may well meaningfully be "".
> Exclude unnecessary URL params on question search

- src/app/components/content/IsaacCodeSnippet.tsx
- src/app/components/elements/Tabs.tsx
- src/scss/cs/button.scss
- src/scss/cs/questions.scss
- src/test/pages/AssignmentProgress.test.tsx
- Fixed behaviour from the redesign causing the [With hints | Without hints] to overlap with the share button in an unreadable way
- Changed the code snippet "View on GitHub" text to the GitHub link itself when printing
- Show tab titles above all individual tabs when printing. The original request was for `codeTabs` specifically, but having tested different options I think this makes sense for all tabs on both sites (helps for a question like [sort_31_v2](https://adacomputerscience.org/questions/sort_31_v2) which isn't using `codeTabs` (or even something like the [About Us](https://adacomputerscience.org/about) page, if you really feel like it)). I also checked viability of doing similar work for our dropdown and button `<Tab>` styles, but they're less straightforward and don't tend to …
> Improve Ada printing behaviour

- src/app/components/content/IsaacInlineRegion.tsx
- src/app/services/questions.ts
This avoids a race condition where the API could not save multiple answers that were submitted at the same time for anonymous users. This is because, for anonymous users, when saving an answer, the API creates a lock using the user's ID, see:
https://github.com/isaacphysics/isaac-api/blob/51296605cef5b532f6f6b90d9a9575001172d4a6/src/main/java/uk/ac/cam/cl/dtg/isaac/quiz/PgQuestionAttempts.java#L92.
> submit inline questions in a sequence

- src/app/components/elements/quiz/QuizContentsComponent.tsx
- src/test/helpers/quiz.ts
- src/test/pages/QuizAttempt.test.tsx
- src/test/pages/QuizPreview.test.tsx
- src/test/pages/QuizView.test.tsx
- src/test/testUtils.tsx
- no longer show "You are viewing the rubric for this test"
- no longer show the "Instructions" heading
See: https://github.com/isaacphysics/isaac-react-app/pull/1457
> remove confusing text from View Test page

- public/assets/phy/icons/redesign/page-generic-bg.svg
- public/assets/phy/icons/redesign/page-generic-fg.svg
- src/app/components/elements/list-groups/ListView.tsx
- src/app/components/pages/Generic.tsx
- src/app/services/constants.ts
- src/scss/phy/icons.scss
Works alongside [this](https://github.com/isaacphysics/isaac-api/tree/redesign%2Fsearchable-book-pages) API change to display book pages in site search.
> Searchable book pages

- src/app/components/content/IsaacContent.tsx
Fixes an issue spotted on the SPC tests owing to identical DOM structures between sections erroneously preserving question state.
Description in the code explains this well:
> Each `<IsaacContent/>` is assumed to be independent, not sharing state with any other. However, React will reuse components if they are the same type, have the same key (or undefined), and exist in the same place in the DOM. If two components A and B meet these criteria, if you switch from component A to component B, any e.g. useStates in B will not initialise as expected, but will retain stale data from A.
>
> This is a problem for any structure where one of several `<IsaacContent/>`s are displayed, e.g. quiz sections, tabs, ... .
>
> To avoid this, we set the key of each <IsaacContent> to its content ID.
More info …
> Prevent stale content components

- .github/workflows/node.js.yml
- src/app/components/elements/cards/BoardCard.tsx
- src/app/components/elements/cards/GameboardCard.tsx
- src/app/components/elements/layout/SidebarLayout.tsx
- src/app/components/pages/Groups.tsx
- src/app/components/site/phy/NavigationMenuPhy.tsx
- src/test/dateUtils.ts
- src/test/pages/MyAssignments.test.tsx
- src/test/pages/MyGameboards.test.tsx
- src/test/pages/QuestionFinder.test.tsx
- src/test/pages/SetAssignments.test.tsx
- src/test/testUtils.tsx
Update the tests to work with the new physics designs.
The only behavioural changes flagged by the test failures were related to the card/table views on Set Assignments and My ~Gameboards~ question decks. Both pages now remember your preference if you navigate away and come back, and My question decks now defaults to card view. I believe both of these changes were intentional so the tests have been changed to expect the new behaviour.
> Update frontend tests for redesign

- src/app/components/elements/Book.tsx
- src/app/components/elements/PageFragment.tsx
- src/app/components/handlers/ShowLoadingQuery.tsx
- src/app/components/pages/NotFound.tsx
This doesn't cover every case, but [window.navigator.onLine](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) cannot cause false negatives so this is a safe improvement over the current system. I've briefly tried it with Firefox, Chrome and Edge, and I trust the documentation that says its widely available. 
If we were sufficiently concerned about edge cases (e.g. being connected to a network but not receiving internet from it), we could try also reading JS errors or pinging the client, but I don't think its worth the effort.
> Show clearer error message when site loaded offline

- src/app/components/elements/layout/SidebarLayout.tsx
- src/app/components/pages/AnvilAppsListing.tsx
- src/app/components/pages/subjectLandingPageComponents.ts
- src/app/components/site/phy/RoutesPhy.tsx
- src/app/services/constants.ts
Implements a breadcrumbed landing page for anvil apps at `{subject}/{stage}/apps`. Only accessible to GCSE and A Level Chemistry at present, will display a short error if you manually set the URL to any other combination.
> Anvil apps listing page

- src/IsaacApiTypes.tsx
- src/app/components/elements/layout/SidebarLayout.tsx
- src/app/components/elements/list-groups/AbstractListViewItem.tsx
- src/app/components/elements/list-groups/ListView.tsx
- src/app/components/pages/Gameboard.tsx
- src/app/services/gameboardBuilder.ts
- src/scss/phy/icons.scss
- src/scss/phy/isaac.scss
- src/scss/phy/list-groups.scss
We've been requested that the question decks should by styled to appear like the question finder. This is mostly a straightforward conversion to ALVIs, but with the following points:
- Content don't want wildcards to be confused with questions, so they have their tags cleared and are portrayed in a neutral context
- (Also some wildcards are absolute links, so I've had to switch from a `<Link>` to `<a>` in the ALVI itself to accommodate 
- In the sidebar: if topic tags are empty, display field tags. If field tags are ALSO empty, don't display the "Topic" heading at all
- While waiting for markbook changes to bring through the new question states, this includes a temporary function to convert between `GameboardItemState` and `CompletionState` to make sure _some_ state is still displayed
> Convert Question Deck layout to ALVI list

- src/app/components/content/IsaacAccordion.tsx
- src/app/components/elements/PageTitle.tsx
- src/app/components/elements/inputs/UserContextPicker.tsx
- src/app/components/elements/modals/QuestionSearchModal.tsx
- src/app/components/navigation/IntendedAudienceWarningBanner.tsx
- src/app/components/pages/Gameboard.tsx
- src/app/components/pages/GameboardBuilder.tsx
- src/app/services/userPreferences.ts
- src/app/services/userViewingContext.ts
- src/test/services/userViewingContext.test.tsx
(Ada): If a teacher has multiple registered contexts set, they should see content highlighted as relevant to them if it is relevant to _any_ of their contexts (we currently just check the first).
> Allow for multiple registered contexts when deciding if content is relevant

- src/app/services/navigation.ts
- src/app/state/slices/doc.ts
Fixes a bug on Ada where reloading a concept page causes the accordions' stage labels to disappear.
This bug was introduced by the move to using slices to handle the topic Redux state. When the concept page is reloaded, the current topic is set to the id of the topic overview page. This PR is a workaround to just not attempt to set the current topic on concept pages at all; I don't _think_ this breaks anything else, but if it does then we might need some bigger changes to the way topic state is handled.
> Fix Ada accordions reloading bug

- src/app/components/navigation/IsaacApp.tsx
- src/app/components/navigation/IsaacScienceMigrationBanner.tsx
Adds a non-dismissible warning banner to Isaac Physics regarding the move to Isaac Science
> Add migration warning banner to Isaac Physics

- src/app/components/pages/SetAssignments.tsx
- src/scss/common/button.scss
- src/scss/phy/button.scss
Use "Unassign" text in place of the "x" button when no other text (e.g. scheduled start date) is present alongside. Also cleans up the button styling a little.
> Ada UX: Assignments modal button

- src/app/components/elements/modals/ActiveModal.tsx
- src/app/components/pages/SetAssignments.tsx
- src/scss/common/modals.scss
- src/scss/cs/isaac.scss
- src/scss/cs/modals.scss
- src/scss/phy/isaac.scss
- src/scss/phy/modals.scss
- src/test/pages/SetAssignments.test.tsx
Adjusts title of Set Assignments modal to create a clearer user flow when creating then setting an assignment. Also slightly modifies the spacing around ActiveModals (Phy+Ada) to better meet designs and center content.
> Ada UX: Set assignments modal

- src/app/components/elements/GameboardBuilderRow.tsx
- src/app/components/elements/modals/QuestionSearchModal.tsx
The main change here is just the first commit, converting the `[]` to a `[{stage: undefined, difficulty: undefined}] AudienceContext[]`.
The rest of this is some mild cleanup, including using `classNames` where appropriate and adding some vertical spacing to the gameboard builder filters - particularly for Ada. These aren't important, so if there are any problems with them I'm happy to abandon them.
> Allow empty audience views to be displayed on the question builder modal

- src/app/components/elements/modals/inequality/InequalityModal.tsx
The `isUserPrivileged` property is intended to be used to inform inequality whether the user is staff or otherwise should have access to certain features and behaviour. Currently, this is only used for overriding `isDetatchable` behaviour (for components like derivatives) that may otherwise be confusing for students to dismantle.
This is **always** enabled for text input (as it may otherwise break things), but had not been propagated for the dragging modal input. This PR enables it for staff.
> Propogate user privilege to inequality modal

- src/app/services/userViewingContext.ts
- src/test/services/userViewingContext.test.tsx
Fixes an issue caused by context code, where a new 'default context' was being created on each call to `useUserViewingContext()` if there was no context defined in Redux (i.e. no context set in account settings). This was causing `useEffect` loops that were dependent on this context (or parts of it) to fire every render.
This was only really noticeable on the gameboard builder since this makes an API call, but this fix should also prevent infinite rerenders on any `useEffect` on the context.
> Fix infinite builder rerender caused by empty context

- src/app/components/content/IsaacContent.tsx
IsaacCodeSnippet is lazy loaded [in order to](https://github.com/isaacphysics/isaac-react-app/commit/87350c86b809e3705b7125c6eb61b3518ad5e505) prevent highlightjs being added to the webpack when unneeded, particularly for Sci. This has meant that to display a code snippet beyond the page's initial load (e.g. in hints), the page had to reload so the component can be loaded. This was also causing the preview renderer to crash.
Wrapping this in a Suspense means only the component itself needs to reload, which is safer behaviour for consistent page state.
> Add Suspense to lazy loaded codeSnippet

- src/app/components/elements/quiz/QuizProgressCommon.tsx
- src/scss/common/assignment-progress.scss
A small extension to my previous changes to add the parts column to the markbook, this change makes both that and the old questions total columns sticky on large screen sizes.
> Make markbook totals columns sticky
