isaacphysics/isaac-react-app

src/app/components/content/IsaacMultiChoiceQuestion.tsx, src/scss/forms.scss
Also use value as `key` instead of index.
=> Fix labeling of IsaacMultiChoiceQuestion for a11y

src/IsaacAppTypes.tsx, src/app/components/content/IsaacTabs.tsx, src/app/components/elements/Tabs.tsx, src/app/components/elements/UserDetails.tsx, src/app/components/elements/UserPassword.tsx, src/app/components/pages/MyAccount.tsx, src/app/components/pages/Registration.tsx, src/app/components/pages/Topic.tsx, src/app/state/actions.tsx
- Adds exam board choice to my account
- Fixes password change alignment
- Adds required fields to my account and register
=> Account details

src/app/components/elements/PageTitle.tsx
Just a suggestion but thought it might be worth doing?
=> Set document.title to reflect page title

src/app/components/elements/UserEmailPreferences.tsx, src/app/components/pages/MyAccount.tsx, src/app/components/pages/Registration.tsx
=> Comments out news and events email preference choosing

src/app/components/elements/TrustedHtml.tsx
The table in the quick question of `/concepts/sys_bool_table_for_circuit#worked_example` when viewed on a mobile is a good example of why this is needed.
=> Table overflow

public/index.html, src/index.tsx
A few alterations to James' page
=> Feature/prettier noscript page  suggestion

src/IsaacApiTypes.tsx, src/app/components/content/IsaacContent.tsx, src/app/components/content/IsaacItemQuestion.tsx, src/app/components/content/IsaacQuestionTabs.tsx, src/scss/questions.scss
Item Questions are somewhere between multiple choice questions and Parsons Problems; you select some of a number of items provided by the question setter.
=> Item Questions

src/IsaacAppTypes.tsx, src/app/components/elements/ActiveModal.tsx, src/app/components/elements/TrueFalseRadioInput.tsx, src/app/components/elements/UserDetails.tsx, src/app/components/elements/UserEmailPreferences.tsx, src/app/components/elements/UserPreferencesModal.tsx, src/app/components/pages/MyAccount.tsx, src/app/components/pages/Registration.tsx, src/app/services/api.ts, src/app/services/constants.ts, src/app/services/notificationManager.ts, src/app/services/scrollManager.ts, src/app/services/validation.ts, src/app/state/actions.tsx, src/app/state/store.tsx
Will require us to run the following command before the release.
`DELETE FROM user_preferences WHERE preference_type='EMAIL_PREFERENCE' AND preference_name IN ('NEWS_AND_UPDATES', 'EVENTS');`
=> Email preferences modal

src/app/components/pages/AllTopics.tsx, src/app/services/constants.ts, src/app/services/tags.ts
Changed the tag comingSoon value from boolean to string to store
the date it is expected to arrive on.
=> Add coming soon dates to all topics

src/app/components/elements/RelatedContent.tsx
Splits into questions and content. May need changes to look better.
=> Split related content into two columns

src/app/components/pages/AdminUserManager.tsx
URNs have been replaced with the school name on the admin manager
page.
=> Show school names to admin manager

src/app/components/handlers/EmailAlterHandler.tsx, src/app/components/navigation/IsaacApp.tsx, src/scss/tables.scss
Allow the verification link to be used without being logged in.
Success/Error messages will be shown depending on the state of
the user and if the verification fails.
=> Allow verification without need to be logged in

src/app/components/pages/Registration.tsx
dateOfBirth is now optional so checkbox disabling needs to check for being undefined not null
=> Registration DoB checkbox enabling

src/app/components/navigation/Header.tsx, src/app/components/navigation/IsaacApp.tsx, src/scss/header.scss
- Adds an id to main in IsaacApp so it can be linked to.
- Same font and size as navbar
- scss used to hide off screen unless focussed on, as suggested here: https://webaim.org/techniques/skipnav/
=> Adds skip to content for keyboard users

src/app/components/navigation/IsaacApp.tsx, src/app/components/pages/Contact.tsx, src/app/components/pages/TeacherRequest.tsx, src/app/services/api.ts, src/app/state/actions.tsx
Awaiting confirmation on wording from copy edit
=> Adds teacher account request page

src/app/components/pages/Gameboard.tsx, src/app/components/pages/GameboardBuilder.tsx
Use query param rather than react-router state to support sharing as a link.
=> Gameboard clone URL query param

src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx, src/app/components/pages/Search.tsx
Shows topics from a page's tag list on the search page where included
=> Adds topic to results in search

package-lock.json, src/app/components/elements/ShareLink.tsx, src/app/components/pages/Concept.tsx, src/app/components/pages/Generic.tsx, src/app/components/pages/MyGameboards.tsx, src/app/components/pages/Question.tsx, src/app/components/pages/SetAssignments.tsx
See: https://github.com/isaacphysics/isaac-router/commit/b1a98497e299fa3f3621b59068c2b9cca28d765e
for router short urls
=> Add shorturls to share links

src/app/components/content/IsaacContent.tsx, src/scss/media.scss
min width taken to match large in _mixins.scss, maybe could be changed
=> Hangs content left or right as in physics

package-lock.json, src/app/components/elements/BreadcrumbTrail.tsx, src/app/components/elements/PageTitle.tsx, src/app/components/pages/Gameboard.tsx, src/app/components/pages/Question.tsx, src/app/services/navigation.ts, src/app/services/tagsAbstract.ts, src/scss/common/gameboard.scss
This is stacked on #179 because it needs some of the same tags logic
=> Physics: show tags and level on gameboard

package-lock.json, src/app/components/elements/Hexagon.tsx, src/app/components/elements/modals/ALevelBookChoiceModal.tsx, src/app/components/elements/modals/IsaacBooksModal.tsx, src/app/components/pages/Alevel.tsx, src/app/components/pages/SetAssignments.tsx, src/app/components/pages/TeacherFeatures.tsx, src/app/components/site/phy/RoutesPhy.tsx, src/app/state/actions.tsx, src/scss/common/focus.scss, src/scss/common/modals.scss, src/scss/phy/menu-page-phy.scss
- Adds site conditional set assignment buttons
- Adds physics books modal
- Adds physics a level book choice modal
- Adds hexagon formatting for hex-buttons
=> Alters set assignment page buttons and adds the book modals

package-lock.json, src/app/components/content/IsaacQuestionTabs.tsx, src/scss/common/fonts.scss, src/scss/phy/subjects.scss
Piggybacks subject check in phy/subjects.scss
Corrects the correct colour (for phy/maths/chem) and makes the text white
=> Adds subject colour and white text for correct on phy

package-lock.json, package.json, src/app/components/elements/InteractiveMap.tsx, src/app/components/pages/Equality.tsx, src/app/components/pages/GameboardBuilder.tsx, src/app/components/pages/MyAccount.tsx, src/app/components/pages/TeacherRequest.tsx
Would like to use the type system a bit more in my account at some point but this is no worse than before.
=> Specify types for TypeScript 3.8

package-lock.json, package.json, src/app/components/content/IsaacSymbolicQuestion.tsx
* 800b76c7 Load equation editor seed
=> Load equation editor seed and possibly more

src/app/components/pages/Registration.tsx, src/app/services/firstLogin.ts
- Alter FIRST_LOGIN_STATE values to make them obvious as we don't use the banner
- Correct a piece of logic for checking first login
=> Alter first login banner behaviour

src/app/components/elements/modals/ALevelBookChoiceModal.tsx, src/app/components/elements/modals/IsaacBooksModal.tsx
- Other modals haven't had this issue of redirecting to a page and not closing, they work on page. 
- Implements the modal close dispatch on link follow
=> Add onClick close modal

package-lock.json, src/app/components/elements/inputs/SubjectInterestTableInput.tsx, src/app/components/elements/inputs/subjectInterestInput.tsx, src/app/components/pages/MyAccount.tsx
Previously rendered before subject preferences returned. Now has useEffect to update and useState to manage controlled checkbox
=> Fix subject preference rendering

src/app/components/pages/Topic.tsx
=> Show multiple linked gameboards from topic pages

src/app/components/content/IsaacSymbolicChemistryQuestion.tsx, src/app/components/content/IsaacSymbolicLogicQuestion.tsx, src/app/components/content/IsaacSymbolicQuestion.tsx, src/app/components/elements/modals/InequalityModal.tsx, src/scss/common/inequality-modal.scss
- Fix infinite re-renderings
- Fix missing seed parsing
- Restore particles for chemistry
- Show question reminder and portrait mode warning
=> August 2020 Inequality improvements

src/app/components/elements/cards/EventCard.tsx
Adds a "Full" badge next to events which have 0 available places and are not waiting list only.
=> Add a "Full" badge to full events

src/app/components/pages/GameboardBuilder.tsx, src/app/state/actions.tsx
If the board is successfully created, log the previous Id and the new Id
=> Log clone board on new board creation

src/app/components/pages/AdminEmails.tsx
This feature overloads the email system dramatically, and use even by accident is unwanted. Remove the ability from the frontend at least.
=> Remove admin email by role

src/app/components/pages/GameboardBuilder.tsx, src/app/services/validation.ts
Simple check for "http" being manually entered into the gameboard ID if provided by a staff member. Won't affect http being present in random generated ID from backend if no ID provided by staff.
=> Try to stop full URLs as gameboard IDs

src/app/components/pages/Alevel.tsx, src/app/components/pages/Gcse.tsx
Add covid lessons cards to gcse and alevel pages
=> Adds COVID-19 Lessons cards to gcse and alevel pages

src/app/components/pages/ClientError.tsx
The motivation for these changes were for improving monitoring and alerting on client errors.
=> Report client errors to the server as a Log Event

public/assets/wildcard.svg, src/app/components/pages/Gameboard.tsx, src/app/services/gameboards.tsx, src/scss/common/gameboard.scss
- Makes in progress/perfect etc messages black on physics
- Adds wildcard
- Adds regex to check if wildcard should be shown
=> Add wildcard for phys and maths book boards

src/app/components/elements/modals/InequalityModal.tsx
We used to have incomplete `d•/dx`-style derivatives only, ignoring whatever was in the first argument. We now include `d^2 y/dx^2` if the first argument of Derivative is a single letter.
=> Show full Derivative(y;x;x) in symbol menu.

src/app/components/elements/modals/InequalityModal.tsx
This only applies when the user is dragging a potential symbol from the menu onto the canvas, and nothing else. The menu can still be closed manually by touching the active tab.
This should address [this ticket](https://tickets.isaacphysics.org/scp/tickets.php?id=22238).
=> Close Inequality menu on drag-out for small screens

src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
Add non-zero levels to Physics question search results
=> Add level to Phy question search results

src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx, src/scss/common/search.scss
- On Physics make question icons in search hexagonal with subject colour
=> Make question icons in search match filter

public/assets/inequality-confirm-cs.svg
As requested by CS. No change for Physics.
=> Change chevron for tick in Inequality submit button

src/app/components/content/IsaacQuestion.tsx
Corresponding API PR: https://github.com/isaacphysics/isaac-api/pull/338
=> Move phy sig fig error feedback to front end

src/app/components/content/QuizQuestion.tsx, src/app/components/elements/modals/QuizSettingModal.tsx, src/app/components/elements/quiz/QuizAttemptComponent.tsx, src/app/components/navigation/IsaacApp.tsx, src/app/components/pages/quizzes/MyQuizzes.tsx, src/app/components/pages/quizzes/QuizAttemptFeedback.tsx, src/app/components/pages/quizzes/QuizDoAssignment.tsx, src/app/components/pages/quizzes/QuizPreview.tsx, src/app/components/pages/quizzes/QuizTeacherFeedback.tsx, src/app/components/pages/quizzes/SetQuizzes.tsx
Cosmetic improvements plus make routes accessible if navigated to directly
=> Quiz neatening

src/app/services/gameboards.tsx
Wildcards on Isaac boards have now been vetted so this can be included.
=> Show wildcards if matches book regex or is an Isaac board

src/IsaacApiTypes.tsx, src/app/components/content/IsaacRegexMatchQuestion.tsx, src/app/components/content/IsaacRegexStringMatchQuestion.tsx, src/app/services/questions.ts
Currently rendered exactly the same as the string match question, have yet to write tests
=> Add frontend support for new regex string match question type

src/app/components/pages/Events.tsx
Simple removal from `Events.tsx`
=> Remove events summer break banner

src/app/components/elements/ShareLink.tsx, src/app/components/pages/Glossary.tsx, src/app/components/pages/MyGameboards.tsx, src/app/components/pages/Question.tsx, src/app/components/pages/SetAssignments.tsx, src/scss/common/boards.scss, src/scss/common/elements.scss
This fixes the problem with the share text being de-attached from the share button, and with the click-away to close not working smoothly
=> Hotfix for share link button

src/IsaacAppTypes.tsx, src/app/components/pages/AdminEmails.tsx
This will help ensure emails have the right values configured if they are being customised or sent via different servers.
Depends on https://github.com/isaacphysics/isaac-api/pull/387
=> Add extra information to the admin email sending page

src/app/components/elements/TrustedHtml.tsx, src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx, src/app/components/pages/Gameboard.tsx
This seems the easiest way to do it
This also renders titles of search results
=> Render question title on gameboards with `TrustedHtml`

src/app/components/pages/Concept.tsx
I believe this addresses the 'gcse transition' page issue for CS
=> Add subtitle to concept pages

src/scss/common/elements.scss
=> Share link overlap fix

src/app/components/elements/ConceptGameboardButton.tsx
This makes it much more visible, as requested by CS
=> Change gameboard from concept link to colourful button

package-lock.json, src/IsaacApiTypes.tsx, src/app/components/elements/panels/TeacherConnections.tsx, src/app/components/pages/Admin.tsx, src/app/components/pages/SetAssignments.tsx, src/app/components/pages/quizzes/MyQuizzes.tsx, src/app/components/pages/quizzes/SetQuizzes.tsx, src/app/services/user.ts, src/app/services/validation.ts, src/app/state/actions.tsx
This shows event managers if test is hidden from teachers, and hides those tests from teachers and students.
Also makes sure that adding student to `hiddenFromRoles` and `visibleToStudent` being `true` do the same thing. We assume that if a test is hidden from teachers, then it is also hidden from students to make the logic easier.
=> Test visibility by role

src/app/services/constants.ts, src/app/services/tagsPhy.ts
These are the changes laid out in phy content's new topic classification schema
=> New physics tags

src/IsaacAppTypes.tsx, src/app/components/elements/views/QuestionProgressCharts.tsx, src/app/components/pages/MyProgress.tsx, src/app/services/constants.ts
Relies on corresponding backend [PR](https://github.com/isaacphysics/isaac-api/pull/401) to add the necessary information to the /progress object
=> Adds stage and difficulty progress donut to Phy

src/app/components/elements/EditContentButton.tsx, src/app/components/elements/PageFragment.tsx, src/app/components/elements/quiz/QuizAttemptComponent.tsx, src/app/components/pages/Concept.tsx, src/app/components/pages/EventDetails.tsx, src/app/components/pages/Question.tsx
Also modify the EditContentButton to have the not-mobile check inside itself to require less DOM components and increase consistency.
=> Add links to the content editor to more page types

src/app/components/site/cs/NavigationBarCS.tsx
Not to merge until CS have completed CE, hopefully by 14th feb
=> Adds link to event formats page

src/app/components/pages/GameboardFilter.tsx
=> Change select placeholders of question finder to "Any"

public/index-cs.html, src/app/components/pages/AllTopics.tsx, src/app/components/pages/Contact.tsx, src/app/components/pages/Events.tsx, src/app/components/pages/GameboardFilter.tsx, src/app/components/pages/Generic.tsx, src/app/components/pages/Glossary.tsx, src/app/components/pages/LogIn.tsx, src/app/components/pages/Registration.tsx, src/app/components/pages/Support.tsx, src/index-cs.tsx
This will need a rethink if/when physics want a customised description too.
=> Add meta descriptions to static pages

src/IsaacApiTypes.tsx, src/IsaacAppTypes.tsx, src/app/components/content/IsaacQuestion.tsx, src/app/components/content/QuizQuestion.tsx, src/app/components/elements/TrustedHtml.tsx, src/app/components/elements/quiz/QuizAttemptComponent.tsx, src/app/components/pages/MyProgress.tsx, src/app/services/fastTrack.ts, src/app/services/questions.ts
Styling might need a change, but the code is done IMO.
This PR also contains two other commits with some refactoring and missing additions from other features. The commit comments explain these.
=> Test question numbering

src/app/components/pages/PreGcse.tsx, src/app/components/site/phy/HomepagePhy.tsx, src/app/components/site/phy/RoutesPhy.tsx
Design agreed with phy, the buttons on the homepage were requested to go vertical on smaller devices
=> Add pre gcse homepage link for phy

src/app/services/constants.ts, src/app/services/tagsPhy.ts
This also adds the new Numbers field, along with 3 new topics.
New ordering outlined in this document: https://docs.google.com/document/d/1dAHq1enPqbTz2xuNu9ZNx7IOQMvZYP3yUKU0Ho0swDU/edit
=> Physics ordering of hexagons on question finder

src/app/components/pages/MyProgress.tsx, src/app/services/questions.ts
Taking the human readable book names from the title of the books respective pages
https://isaacphysics.org/books/maths_book_gcse
https://editor.isaacphysics.org/#!/edit/master/content/books/phys_book_step_up_gcse_22/phys_book_step_up_intro.json
=> Optimistic addition of new books to My Progress

src/app/components/content/IsaacHorizontal.tsx
See `/questions/phys_linking_31_q` Part B and `/questions/ed646fd4-35d3-4e46-962b-c3a11c165a55` Part Q, comparing staging against this branch. 
On this branch, the pages look like the following:
=> Fix horizontal layout font and margins

src/app/components/elements/modals/IsaacBooksModal.tsx, src/app/components/elements/modals/QuestionSearchModal.tsx, src/app/components/elements/views/ProgressBar.tsx, src/app/components/pages/GameboardBuilder.tsx, src/app/components/pages/MyProgress.tsx, src/app/services/questions.ts
Also reorder books in everywhere to match ordering in books modal
=> Release Linking concepts book everywhere

src/app/components/elements/modals/QuestionSearchModal.tsx, src/app/components/pages/GameboardFilter.tsx, src/app/services/constants.ts
This does not remove P3 and C3 from the iconography nor the help tooltip.
=> Remove P3 and C3 from difficulty filters for CS

src/app/components/elements/GameboardBuilderRow.tsx, src/app/services/userContext.ts
This viewing logic code is getting quite complex and so I should revisit it to see if we can make it easier to understand through better documentation, identifier renaming and unit-tests.
=> Show all valid exam boards in board builder

src/app/components/site/cs/HomepageCS.tsx, src/app/components/site/cs/NavigationBarCS.tsx, src/app/services/tagsCS.ts
Also remove GCSE to A Level transition strand and related topics
=> Remove BETA badge from GCSE

src/app/components/elements/modals/QuestionSearchModal.tsx, src/app/components/navigation/IsaacApp.tsx, src/app/components/pages/ClientError.tsx
This seems to fix the problem, but I think it only works in the case that the main chunk (and whatever chunk(s) fetches the outdated chunk(s)) changes as well.
To test this, we need to: 
- bring this branch up on `test`
- login to the test site in a browser and navigate to the homepage (don't visit My Progress)
- change something in `MyProgress.tsx`
- build and deploy to `test` again
- without reloading the tab, navigate to My Progress
The page should show a "Loading..." message and reload, and either My Progress should render as expected, or the site goes in an infinite loop of reloading and the thing that I mentioned above is the case.
This needs to be done with an actual nginx instance (and not just with a python server locally) so all the assets are given the same cache control …
=> Lazy loading outdated chunks causing errors

src/app/components/content/IsaacNumericQuestion.tsx, src/app/components/content/IsaacSymbolicLogicQuestion.tsx, src/app/components/content/IsaacSymbolicQuestion.tsx, src/app/components/pages/Equality.tsx
Specifically anywhere with tooltips next to an answer input box
=> Change tooltip placement to "top" 

src/app/components/pages/GameboardBuilder.tsx
Problem was reported by CS and is quite urgent as it will be featured in a demo presentation tomorrow.
The fix is small but also addresses a few exhaustive deps eslint warnings.
There is another useEffect in that file that needs looking at but it is separate from the concerns of this hotfix.
=> Fix CS gameboard from concepts feature

src/app/components/elements/modals/TeacherEventConfirmationModal.tsx, src/app/components/elements/modals/UserBookingModal.tsx, src/app/components/pages/EventDetails.tsx
This modal pops up if you try to book on a teacher-only event as a student. 
The first commit is the feature addition, the second commit is a small refactor to imports.
=> Teacher status confirmation modal for teacher-only events

src/IsaacAppTypes.tsx, src/app/components/pages/SetAssignments.tsx
Instead of just using `isStaff`.
I've also added the beta feature to all of the segue config files on the server 👍
=> Allow user to schedule assignments based on a beta feature flag

src/app/components/elements/inputs/SchoolInput.tsx
Ensure that we fetch schools that line up with the most recent search term, by setting the `trailing` option to `true` in the lodash `throttle` HOF. Also adds some type info.
=> Always call `searchSchools` at the end of throttling window

src/app/components/pages/AssignmentProgress.tsx, src/app/services/assignments.ts, src/scss/common/assignment-progress.scss
To make it clear which assignments are live.
=> De-emphasise scheduled assignments in assignment progress

deploy.py
Also adds commands that check for "penultimate" api version(s), new db migrations, and new config changes.
=> Allow deploy script to execute commands itself (after prompting user)

src/app/components/elements/modals/RequiredAccountInformationModal.tsx, src/app/services/siteConstants.ts
Fix race condition when loading initial user state in `RequiredAccountInfoModal`.
(Change base branch to `master` if we merge `the-analytical-engine` first)
=> Required account info modal race condition

package.json, src/app/components/content/IsaacGraphSketcherQuestion.tsx, src/app/components/elements/modals/GraphSketcherModal.tsx, src/app/components/pages/GraphSketcher.tsx, src/scss/common/graph-sketcher-modal.scss, yarn.lock
This adds some content-approved misc changes to the graph sketcher, along with a bug fix for annoying "phantom" curves that seemed to stick around.
=> Reset button and phantom data fix 

src/app/components/elements/modals/GraphSketcherModal.tsx, src/app/components/pages/GraphSketcher.tsx, src/scss/common/graph-sketcher-modal.scss
Some small misc improvements requested by Matthew in the content team.
=> Graph sketcher debug mode improvements

src/app/components/pages/AssignmentSchedule.tsx, src/app/components/pages/SetAssignments.tsx
Specifically, teachers. This only affects physics since it was enabled on Ada already.
Also allows teachers to assign to multiple groups at once.
Requires https://github.com/isaacphysics/isaac-api/pull/541
=> Enable schedule assignment feature for any role that can set assignments

src/app/components/content/IsaacContent.tsx
Means content can clear floating elements as and when required
=> Add clearfix layout content block

src/app/components/elements/panels/TeacherConnections.tsx, src/app/components/pages/AssignmentProgress.tsx, src/app/components/pages/Groups.tsx, src/app/components/pages/MyAssignments.tsx, src/app/components/pages/MyGameboards.tsx, src/app/components/pages/SetAssignments.tsx, src/app/components/pages/quizzes/MyQuizzes.tsx, src/app/components/pages/quizzes/SetQuizzes.tsx
Adds help fragments to various pages.
=> Add help fragments to Physics pages

compose, compose-etl, compose-live, deploy.py
Updates the layout of config directories to reflect changes to the SOPS deployment script.
=> Update config directories

src/app/services/constants.ts, src/app/services/questions.ts
Now it always displays varepsilon in the LaTeX preview
=> Use varepsilon instead of epsilon for equality LaTeX output

src/app/components/elements/modals/GraphSketcherModal.tsx, src/scss/common/graph-sketcher-modal.scss, src/scss/common/inequality-modal.scss
Just copies the implementation in the `InequalityModal` component.
=> Add Inequality-like question text display to graph sketcher

src/app/components/elements/AccountTypeMessage.tsx, src/app/components/elements/modals/RequiredAccountInformationModal.tsx, src/app/components/elements/panels/UserDetails.tsx, src/app/components/navigation/IsaacApp.tsx, src/app/components/pages/TeacherAccountSelfUpgrade.tsx, src/app/components/site/cs/RoutesCS.tsx, src/app/components/site/phy/RoutesPhy.tsx, src/app/services/siteConstants.ts, src/app/state/slices/api/userApi.ts, src/test/pages/authorisationRedirects.test.ts
Adds a page to Ada through which users can upgrade themselves to teacher accounts without manual approval.
=> Allow upgrades to teacher accounts without manual approval

src/app/components/content/IsaacQuestion.tsx, src/app/services/localStorage.ts, src/app/services/validation.ts
This uses a daily (UTC-based) window to align with that of our Plausible instance.
=> Notify Plausible of the first question attempt of each day

public/assets/phy/bin-black.svg, src/app/components/pages/Groups.tsx, src/app/state/slices/api/groupsApi.ts, src/scss/phy/button.scss, src/test/pages/Groups.test.tsx
* Replaces group deletion button 'x' icon with bin (adds new black bin icon for Physics)
* Only shows group deletion button for archived groups
* Replaces user removal button with link
=> Group deletion UI changes in Manage Groups

src/app/components/pages/GameboardFilter.tsx
Adds a checkbox toggle to show/hide book questions (default show) when searching for questions in gameboard creation.
=> Add checkbox in search to hide book questions

src/app/components/content/IsaacNumericQuestion.tsx
Give feedback under numeric question attempts before submitting if the formatting is incorrect (similar functionality exists already for symbolic questions).
=> Immediate invalid numeric question feedback

src/IsaacAppTypes.tsx, src/app/components/elements/GameboardBuilderRow.tsx, src/app/components/elements/modals/QuestionSearchModal.tsx, src/app/components/pages/GameboardBuilder.tsx, src/app/services/constants.ts
Adds undo and redo buttons to gameboard editing for easier workflow.
Just the undo was requested, but it's then equally easy to make mistakes using that, so a redo was added too.
=> Undo gameboard question deletion

src/app/components/pages/GameboardFilter.tsx
The gameboard filter menu has two expand buttons which previously had no effect (though did in staging-2). This restores said functionality.
=> Collapse gameboard filters menu when pressed

src/app/components/content/IsaacNumericQuestion.tsx, src/app/components/content/IsaacQuestionValidator.tsx, src/app/components/content/IsaacSymbolicLogicQuestion.tsx, src/app/components/content/IsaacSymbolicQuestion.tsx, src/app/components/pages/Equality.tsx
Refactors Equality and the Numeric, Symbolic, SymbolicLogic IsaacQuestions to reuse shared debouncing code.
=> Move common debouncing code into shared validator

src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
Checked other usages of summary to verify that changes are safe.
=> Hide summary in CS search

src/app/components/elements/cards/BoardCard.tsx, src/app/components/pages/MyGameboards.tsx, src/app/components/pages/SetAssignments.tsx, src/scss/phy/boards.scss
Reordered a lot of the information on the card to follow an expected order.
=> Redesign Isaac Gameboard card view

src/app/components/elements/panels/TeacherConnections.tsx, src/app/services/miscUtils.ts, src/scss/common/my-account.scss
Adds a magnifying glass button that opens a search bar to the side when pressed, or replaces the box title if too little space.
=> Add search bars to a user's connections lists

src/app/components/elements/list-groups/ListGroupFooter.tsx
Additional semi-colon to comply with ESLint
=> Remove Extraordinary Problems footer link

package.json, src/app/components/elements/modals/GraphSketcherModal.tsx, src/scss/common/graph-sketcher-modal.scss, yarn.lock
- Option to show slop in debug mode
- Prevent overlapping of debug mode button and linear style button on xs-size devices
=> Graph sketcher UI improvements

package.json, src/IsaacApiTypes.tsx, src/app/components/content/IsaacGraphSketcherQuestion.tsx, src/app/components/elements/modals/GraphSketcherModal.tsx, src/scss/common/graph-sketcher-modal.scss, yarn.lock
Passes through custom axis labels received from the API to the sketcher for display. Also reorders the sketcher UI to prevent button / text field overlaps, particularly in debug mode.
=> Support custom axis labels in sketcher

src/app/services/searchResults.ts, src/scss/common/list-groups.scss
Adds magic search results for:
Both sites:
- Glossary
- Question finder
- A-level resources
- My progress
Isaac:
- My Gameboards
- Events
- Essential Pre-Uni/GCSE physics
- Senior Physics Challenge
- Essential books
- Quantum primer book
Ada:
- My Quizzes
=> More magic search results

src/app/components/elements/Accordion.tsx
Prevent spamming of accordion headers logging excessively to database
=> Debounce accordion opening log events

src/app/components/content/IsaacContentValueOrChildren.tsx, src/app/components/content/IsaacHorizontal.tsx, src/scss/common/accordions.scss, src/scss/common/media.scss
- Adjust padding for horizontal layout div's
- Adjust padding and margin for figure panels
=> Fix the indentation issues with horizontal layouts on certain pages

src/app/components/elements/inputs/SchoolInput.tsx, src/app/components/elements/panels/UserDetails.tsx, src/app/components/pages/MyAccount.tsx
- Add a modal to help teachers when changing schools
- Fix ESLint warnings for yet another file
=> Changing schools modal

src/IsaacApiTypes.tsx, src/app/state/slices/api/assignmentsApi.ts, src/app/state/slices/api/quizApi.ts
- Add a modal to help teachers when changing schools
- Remove eslint ignore-any comment
- Rename AssignmentFeedbackDTO to AssignmentStatusDTO
=> Align assignment status DTOs in back- and frontend

src/app/components/elements/quiz/QuizProgressCommon.tsx, src/app/components/pages/AssignmentProgress.tsx, src/app/components/pages/quizzes/QuizTeacherFeedback.tsx, src/scss/common/assignment-progress.scss
- Normalise `isQuiz` terminology to be consistent with the rest of the codebase (i.e. is this a _test_), thus fixing discrepancy
- Prevent table overflowing bounding box, scroll instead
- Fix sort buttons being too low
=> Clean buggy behaviour on assignment progress table

src/scss/common/footer.scss, src/scss/phy/footer.scss
As to meet WCAG guideline G183.
=> Underline footer links on hover

src/app/components/elements/CardGrid.tsx, src/app/components/pages/quizzes/MyQuizzes.tsx, src/scss/common/quiz.scss
Adds a CardGrid component for correctly managing the heights of elements in a grid, as to replace `block-grid`. Applies this to My Tests.
=> My Tests: same height grid elements

src/app/components/elements/Carousel.tsx, src/app/components/elements/NewsCarousel.tsx, src/app/components/elements/cards/NewsCard.tsx, src/app/components/pages/News.tsx, src/scss/common/cards.scss, src/scss/common/carousel.scss
- Align pods to be the same height;
- Align content within the pods to start at the same height;
- Paragraph text that would otherwise overflow is cut off with an ellipsis (no such example exists currently).
=> News Pods refactor

src/app/components/elements/inputs/DateInput.tsx
- Display the pre-selected year despite of year range
=> Fix date input visual bug when pre-selected year out of range

package.json, src/app/components/elements/inputs/EmailInput.tsx, src/app/components/elements/inputs/ProgrammingLanguageInput.tsx, src/app/components/elements/inputs/SchoolInput.tsx, src/app/components/elements/inputs/SetPasswordInput.tsx, src/app/components/elements/inputs/UserContextAccountInput.tsx, src/app/components/elements/modals/TeacherConnectionModalCreators.tsx, src/app/components/elements/panels/UserContent.tsx, src/app/components/elements/panels/UserProfile.tsx, src/app/components/navigation/IsaacApp.tsx, src/app/components/pages/RegistrationAgeCheck.tsx, src/app/components/pages/RegistrationAgeCheckFailed.tsx, src/app/components/pages/RegistrationRoleSelect.tsx, src/app/components/pages/RegistrationSetDetails.tsx, src/app/components/pages/RegistrationSuccess.tsx, src/app/components/pages/RegistrationTeacherConnect.tsx, src/app/components/pages/RegistrationVerifyEmail.tsx, src/app/services/validation.ts, src/app/state/actions/index.tsx, src/scss/cs/button.scss, src/scss/cs/forms.scss, src/scss/cs/isaac.scss, src/scss/cs/my-account.scss, yarn.lock
* Add components and static routes for student flow: age verification, teacher connection
* Use NPM package for RPF design system instead of loading from URL
* Make the correct fields required and fix some validation issues
* Fix form submit button styling
=> Implement Ada student flow

src/app/services/quiz.ts
=> Use 'Test' in set test toast modal on both sites

src/app/state/actions/quizzes.tsx
Slows down the rate at which test attempt submissions are automatically saved.
=> Throttle dirty test attempt submission

src/app/components/pages/MyAccount.tsx
- Improve readability of the modal text
- Link back to Teacher FAQ
=> Improve the changing school popup modal

src/app/components/elements/ConceptGameboardButton.tsx, src/app/components/elements/RelatedContent.tsx, src/app/components/pages/MyAccount.tsx, src/scss/cs/header.scss
- Improve readability of the modal text
- Link back to Teacher FAQ
- Display related questions beyond a users specification
- Improve wording for header
=> Display related questions outside a user's specification

src/app/components/site/cs/HomepageCS.tsx, src/scss/common/cards.scss, src/scss/cs/homepage.scss, src/scss/cs/pages.scss
* Design updates 
* Restore featured news item
=> Ada homepage hero updates

src/app/components/elements/Accordion.tsx, src/app/components/elements/inputs/UserContextPicker.tsx, src/app/components/pages/Concept.tsx, src/app/components/pages/Search.tsx, src/app/components/pages/Topic.tsx, src/scss/common/accordions.scss, src/scss/common/pages.scss, src/scss/common/questions.scss
Aligns content in mobile, tries to keep consistency between UserContextPicker in all 3 use cases
=> Context picker mobile layout improvements

src/app/components/pages/Events.tsx, src/app/services/constants.ts, src/app/services/events.tsx, src/app/services/userContext.ts, src/app/state/slices/api/eventsApi.ts
- Adds All Stages option, defaults filter to this instead of GCSE
- Adds the remaining stages (Year 7&8, Year 9)
=> Events stage filter bug fixes

src/app/components/pages/quizzes/MyQuizzes.tsx, src/scss/common/quiz.scss
- Adds `#in-progress`, `#completed` and `#practice` anchors to My Tests
- Adds a filter-by-name box to #practice, with a sharable link
=> Add hash anchors and name filtering to My Tests

src/app/services/constants.ts, src/app/services/tagsCS.ts
PR to hold this change until we get the go-ahead from the content team.
=> Add Ada projects strand

src/app/components/pages/QuestionFinder.tsx
- Encode the search string as a URI Component
- Update search string URL component only on enter
=> QuestionFinder search filter improvements

src/app/components/pages/Concept.tsx, src/app/components/pages/Question.tsx, src/app/components/pages/Topic.tsx
- Remove staff restriction on the QuestionFinder page
- Only display banner on Ada
=> Remove intended audience warning banner from Physics

src/IsaacApiTypes.tsx, src/app/components/navigation/SupersededDeprecatedWarningBanner.tsx, src/app/components/pages/Concept.tsx
Also fix a weird typing error (likely copy-paste mistake!) in the Concept page code.
=> Move deprecated and superseded types to page-level

src/app/components/content/IsaacVideo.tsx, src/app/components/handlers/InterstitialCookieHandler.tsx
Adds logging to YT embeds as to record how often videos are blocked. Also converts the phy homepage video to a standard IsaacVideo to align it with the others.
=> Add Plausible logging for YouTube iframe failure

src/app/components/site/phy/HeaderPhy.tsx
=> Fix off-white header background colour

src/scss/cs/accordions.scss, src/scss/cs/button.scss, src/scss/cs/isaac.scss, src/scss/cs/table.scss
- Implement small style improvements for Ada
- increase margin below h4 in accordions
=> Small Ada style changes

src/scss/common/accordions.scss
See https://staging.adacomputerscience.org/topics/databases.
=> Fix padding on horizontal layout columns

src/app/components/elements/inputs/SchoolInput.tsx, src/app/components/elements/inputs/StyledCheckbox.tsx, src/app/components/elements/inputs/UserContextAccountInput.tsx, src/app/components/elements/modals/UserContextReconfirmationModal.tsx, src/app/components/elements/panels/UserBetaFeatures.tsx, src/app/state/middleware/notificationManager.ts, src/scss/common/checkbox.scss, src/scss/common/my-account.scss, src/scss/cs/my-account.scss, src/scss/phy/forms.scss, src/test/pages/UserContextReconfirmationModal.test.tsx
Fixes a number of issues with components lifted from My Account, then implements them into a redesigned new academic year modal.
You can test this by changing the `else if (...)` [here](https://github.com/isaacphysics/isaac-react-app/blob/master/src/app/state/middleware/notificationManager.ts#L40) to just `else if (true)`. 
Confirmed Ada & physics are happy with the changes.
=> New academic year modal redesign

src/IsaacApiTypes.tsx, src/IsaacAppTypes.tsx, src/app/components/elements/quiz/QuizProgressCommon.tsx, src/app/components/pages/AssignmentProgress.tsx, src/app/components/pages/SingleAssignmentProgress.tsx, src/app/components/pages/quizzes/QuizTeacherFeedback.tsx, src/app/services/progress.ts, src/app/state/slices/api/assignmentsApi.ts, src/app/state/slices/api/utils.ts
Makes a distinction in the type of studentProgress depending on whether the user has authorised access (`AuthorisedAssignmentProgress`) or not (base class, `AssignmentProgressDTO`).
=> Fix assignment progress types

src/app/components/navigation/DowntimeWarningBanner.tsx
Add downtime warning banner for database maintenance on 10th August.
=> Update downtime warning banner

src/app/components/elements/panels/StreakPanel.tsx
On Isaac Physics, hide daily streaks under 14 days.
=> Hide daily streaks under 14 days

src/app/components/pages/quizzes/SetQuizzes.tsx, src/scss/common/quiz.scss
Changed 'Set Tests' page format to **RS.Cols** to allow for consistent 'Set Test' button sizes.
=> Fix 'Set Test' button width and height

src/app/services/validation.ts
Change frontend email validation to match regex used in backend.
=> Improve email regex

src/app/components/content/IsaacQuestion.tsx
Reuses the "Partly correct..." orange feedback from inline questions for cloze questions, if at least one correct and one incorrect answer exists in the feedback.
=> Enable partial correctness on cloze questions

src/app/components/content/IsaacContent.tsx, src/app/components/content/IsaacInlineRegion.tsx, src/app/components/content/IsaacQuestion.tsx, src/app/components/elements/inputs/InlineNumericEntryZone.tsx, src/app/components/elements/inputs/InlineStringEntryZone.tsx
Modifies how inline question state is managed across both question load and update to restore functionality of aggregate operations on `pageQuestions` when inline questions exist on a page.
=> Inline Question Redux Improvement

src/app/components/content/IsaacQuestion.tsx
Make the 'Check my answer' button full-width on small screens and half-width otherwise.
=> Fix submit button scaling

src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx, src/app/components/pages/QuestionFinder.tsx
Add boolean to allow ignoring of intended audience in ContentSummaryListGroupItem
=> Ignore intended audience emphasis in the QF

src/IsaacApiTypes.tsx, src/app/components/content/IsaacSymbolicChemistryQuestion.tsx, src/app/components/content/IsaacSymbolicQuestion.tsx, src/app/services/questions.ts, src/react-app-env.d.ts, src/scss/common/questions.scss
- Implement text entry for Chemistry questions
- Implement nuclear text entry
- Improve feedback for users
=> Chemistry and nuclear text entry

src/app/components/content/IsaacCard.tsx, src/scss/phy/menu-page-phy.scss
On physics, make all cards in the same row have the same height. Also make some spacing changes within cards.
=> Make card heights consistent

src/app/components/content/IsaacNumericQuestion.tsx, src/test/components/content/IsaacNumericQuestion.test.tsx
Applies the numeric cleanup suggested in https://github.com/isaacphysics/isaac-react-app/pull/1154, as to reject commas in numeric questions and tidy up the code
=> Numeric validation cleanup

src/app/state/actions/index.tsx
This means the session expiry time is set properly.
=> Request current user for MFA and email verification required users

src/app/components/elements/modals/IsaacBooksModal.tsx, src/app/components/elements/modals/QuestionSearchModal.tsx, src/app/components/elements/panels/QuestionFinderFilterPanel.tsx, src/app/components/elements/views/ProgressBar.tsx, src/app/services/questions.ts
Add Pre-University Mathematics for Sciences (2nd edition) to various lists.
=> Add new maths book

src/app/components/navigation/LLMFreeTextQuestionInfoBanner.tsx, src/app/components/navigation/ResearchNotificationBanner.tsx
These copy changes have been approved by the Department's Ethics Committee and RPF's copy edit team.
=> Update notification banners for clarity

src/app/components/content/IsaacClozeQuestion.tsx, src/app/components/elements/markup/portals/InlineDropZones.tsx
Use dropdowns for cloze questions on all small screens and on medium-sized touchscreens.
=> Change cloze dropdown breakpoint

src/app/components/pages/Question.tsx, src/scss/common/print.scss
Remove the shadows around non-accordion questions and above the license disclaimer.
=> Remove print shadows

src/app/components/elements/SortableItemHeader.tsx, src/app/components/pages/quizzes/QuizTeacherFeedback.tsx
Adds missing class average calculation for Tests.
=> Assignment Progress: class average attempts for Tests

src/app/components/pages/CSProjects.tsx, src/app/components/pages/OnlineCourses.tsx, src/app/components/site/cs/HeaderCS.tsx, src/app/components/site/cs/RoutesCS.tsx
Adds a Projects page to Ada at `/projects`.
Most of the code has been reused from Online Courses; this fixes a bug with this code relating to StrictMode duplicating pods.
=> Ada Projects page

src/app/components/elements/cards/IconCard.tsx, src/app/components/pages/StudentResources.tsx, src/app/components/pages/TeacherResources.tsx
Pulls student challenges via the pod query, using the `student_challenges` tag.
=> Fetch Ada student challenges automatically

src/app/components/pages/QuestionFinder.tsx
Move question finder logging from the app to the API.
=> Remove QF logging from app

src/app/components/content/IsaacSymbolicLogicQuestion.tsx, src/scss/cs/questions.scss
Enable text entry on symbolic logic questions for all users, and make it look slightly less cursed than it did before.
=> Boolean logic text entry for all

src/IsaacAppTypes.tsx, src/app/components/site/phy/NavigationMenuPhy.tsx
The nav dropdowns were not opening on occasion when quickly moving the mouse between a pair of them.
=> Fix dodgy nav dropdowns

public/assets/phy/icons/redesign/page-lessons-bg.svg, public/assets/phy/icons/redesign/page-lessons-fg.svg, src/app/components/elements/layout/SidebarLayout.tsx, src/app/components/pages/Concepts.tsx, src/app/components/pages/LessonsAndRevision.tsx, src/app/components/pages/QuestionFinder.tsx, src/app/components/pages/QuestionPacks.tsx, src/app/components/pages/QuickQuizzes.tsx, src/app/components/pages/SubjectLandingPage.tsx, src/app/components/pages/quizzes/PracticeQuizzes.tsx, src/app/components/site/phy/RoutesPhy.tsx, src/app/services/context.ts, src/app/services/pageContext.ts, src/app/services/search.tsx, src/scss/phy/icons.scss
Adds routes to subject-specific versions of:
- Question Finder
- Concepts listing
- Practice tests
Adds routes to and basic implementations of:
- Lessons and revision
- Quick quizzes
- Question packs
=> Subject-specific pages

src/app/components/content/IsaacVideo.tsx, src/app/components/elements/Accordion.tsx, src/app/components/elements/inputs/StyledTabPicker.tsx, src/app/components/pages/Support.tsx, src/scss/common/accordions.scss, src/scss/common/elements.scss, src/scss/cs/accordions.scss, src/scss/phy/accordions.scss, src/scss/phy/color-theme.scss, src/scss/phy/sidebar.scss
- Restores IsaacVideo to tab-less format (we shall reuse the original code in IsaacTabs soon!)
- More broadly restructure accordions to remove years of bloat (TODO: check Ada!)
- Reuse styled tab picker component for the sidebar
=> FAQ suggestions

src/app/components/elements/inputs/StyledTabPicker.tsx, src/app/components/elements/layout/SidebarLayout.tsx, src/app/components/pages/MyAccount.tsx, src/scss/common/elements.scss, src/scss/phy/color-theme.scss, src/scss/phy/sidebar.scss
Pulls the code for a sidebar tab picker into its own reusable component.
=> Reusable tab picker component

src/app/components/elements/inputs/StyledCheckbox.tsx, src/app/components/elements/list-groups/AbstractListViewItem.tsx, src/app/components/elements/panels/QuestionFinderFilterPanel.tsx, src/app/components/elements/svg/HierarchyFilter.tsx, src/scss/common/checkbox.scss, src/scss/phy/checkbox.scss
Applies some suggestions to the question finder redesign branch.
=> QF Suggestions

src/app/components/pages/EventDetails.tsx, src/scss/common/events.scss
This does technically change one part of the Ada event page, in that the map will get smaller on "md" screens, but I think this is an improvement should that page ever exist anyway so 🤷
=> Move Image and Map to their own object

src/app/components/pages/SubjectLandingPage.tsx, src/app/services/pageContext.ts, src/test/pages/SubjectLandingPage.test.tsx
Turned out, the bug was only present when no user was logged in. I cannot explain why. On the upside, the react-testing-toolkit tests did reproduce the issue after all, they just needed to be adjusted so the user is logged out.
=> Bug/redesign 2024/subject landing page infinite requests

src/app/components/elements/layout/SidebarLayout.tsx
Minor changes to ensure all assignments/tests-related sidebars use similar styling.
=> Make assignments/tests sidebars consistent with each other

src/app/components/elements/StudentDashboard.tsx, src/app/components/elements/panels/TeacherConnections.tsx, src/app/components/pages/RegistrationTeacherConnect.tsx, src/test/pages/Groups.test.tsx, src/test/pages/MyAccount.test.tsx
- Fix a redesign bug where entering a space on the student dashboard caused an error
- Add some additional checks for group code length & valid characters
- Remove some duplicated code
(PR is into `redesign-2024`, I don't think this is worth changing on `master`)
=> Improve group code validation

src/app/components/site/phy/HomepagePhy.tsx, src/scss/common/accessibility.scss, src/scss/common/scroll-button.scss, src/scss/phy/color-theme.scss, src/scss/phy/icons.scss
A couple of smaller general changes to the redesign:
- Replace lorem ipsum homepage text with subject-specific suggestions
- Add gentle icon hover colour transitions to keyline buttons
- Fix issues with scroll-to-top
=> Redesign: General improvements 3

src/app/components/elements/GameboardBuilderRow.tsx, src/app/components/pages/GameboardBuilder.tsx, src/scss/cs/button.scss
On Ada: Use the same icon as deleting an assignment for deleting gameboard questions.
=> Use delete icon on gameboard builder

src/app/state/middleware/userConsistencyChecker.tsx
Instead of attempting to record `USER_CONSISTENCY_CHECKING_FAILED` events via the API, record these to Plausible. The API has actually been rejecting any attempts to log these events since 2024.
An example of a `USER_CONSISTENCY_CHECKING_FAILED` event can now be found on the [Dev Plausible Dashboard](https://plausible.isaacphysics.org/dev.isaacphysics.org?goal=exception&props=%7B%22description%22%3A%22user_consistency_checking_failed%22%7D). I've tested that an event now gets successfully recorded by deploying the code from this branch to `dev`, and attempting to log in while blocking local storage access in Chrome. I have since reverted `dev` to `master`, so anybody attempting to reproduce the test on `dev` would need to perform another deploy first.
I would like to highlight I've made …
=> `user_consistency_checking_failed` to Plausible

src/IsaacAppTypes.tsx, src/app/components/elements/modals/QuestionSearchModal.tsx, src/app/components/pages/QuestionFinder.tsx, src/app/components/pages/SubjectLandingPage.tsx
We can use this to decide whether to log and how to filter the questions in the API.
(Review this ignoring whitespace!)
=> Add querySource to all use of question searches

src/app/components/navigation/BetaSiteBanner.tsx, src/app/components/navigation/DismissibleBanner.tsx, src/app/components/navigation/IsaacApp.tsx, src/app/components/navigation/IsaacScienceLaunchBanner.tsx
Replaces the old warning banner with a dismissible info banner with a link to how the change may affect users/schools.
=> Add new launch banner

src/app/components/elements/inputs/SchoolInput.tsx, src/app/components/pages/EventDetails.tsx
Fixes two problems with EventDetails:
1. Restructures the file to avoid nesting components. This fixes an issue where rerenders caused by typing in the input field reload the entire form, scrolling back up to the top and preventing further typing.
2. Prevents making an API request on rerender of <SchoolInput/> to obtain school information from the URN, provided that information has not changed.
=> EventDetails form refactor

src/app/components/elements/modals/QuizSettingModal.tsx, src/scss/common/forms.scss, src/scss/cs/forms.scss
Rework the Set Quiz modal to use the new preferred form format, whereby the submission button is always enabled, but clicking it highlights any invalid fields in red, preventing submission.
=> Ada UX: Improve form feedback

src/app/services/searchResults.ts
- Add some new shortcuts based on common searches
- Remove some shortcuts that are deprecated or unnecessary because they're included in normal search results
=> Update search shortcuts
